# Legitimate Project Structure Indicators
# These patterns indicate professional development practices
# Useful for differential ML analysis

traits:
  # Has README file (detected via package.json main pointing to index)
  - id: legitimate/has-index-entry
    description: Package has standard index entry point
    criticality: inert
    confidence: 0.8
    file_types: [packagejson]
    condition:
      type: string
      regex: '"main":\s*"(?:index\.js|dist/|lib/|src/)'

  # Has types entry point
  - id: legitimate/has-types-entry
    description: Package has TypeScript types entry
    criticality: inert
    confidence: 0.9
    file_types: [packagejson]
    condition:
      type: string
      regex: '"types":\s*"|"typings":\s*"'

  # Has module entry (ESM)
  - id: legitimate/has-module-entry
    description: Package has ESM module entry
    criticality: inert
    confidence: 0.85
    file_types: [packagejson]
    condition:
      type: string
      regex: '"module":\s*"'

  # Has sideEffects field
  - id: legitimate/has-side-effects
    description: Package declares sideEffects (tree-shaking support)
    criticality: inert
    confidence: 0.85
    file_types: [packagejson]
    condition:
      type: string
      regex: '"sideEffects":\s*(?:false|\[)'

  # Has browserslist
  - id: legitimate/has-browserslist
    description: Package has browser target configuration
    criticality: inert
    confidence: 0.8
    file_types: [packagejson]
    condition:
      type: string
      exact: '"browserslist":'

  # Has multiple entry points
  - id: legitimate/has-multiple-entries
    description: Package has multiple entry points (complex library)
    criticality: inert
    confidence: 0.85
    file_types: [packagejson]
    condition:
      type: yara
      source: |
        rule multiple_entries {
          strings:
            $main = "\"main\":" ascii
            $module = "\"module\":" ascii
            $exports = "\"exports\":" ascii
            $types = "\"types\":" ascii
          condition:
            2 of them
        }

  # Uses npm scripts for development workflow
  - id: legitimate/has-dev-workflow
    description: Package has development workflow scripts
    criticality: inert
    confidence: 0.85
    file_types: [packagejson]
    condition:
      type: yara
      source: |
        rule dev_workflow {
          strings:
            $test = "\"test\":" ascii
            $build = "\"build\":" ascii
            $lint = "\"lint\":" ascii
            $format = "\"format\":" ascii
            $dev = "\"dev\":" ascii
            $start = "\"start\":" ascii
          condition:
            3 of them
        }

  # Has CI badge indicators (usually in description or homepage)
  - id: legitimate/ci-badge-reference
    description: References CI service (professional project)
    criticality: inert
    confidence: 0.8
    file_types: [packagejson]
    condition:
      type: string
      regex: 'travis-ci\\.org|circleci\\.com|github\\.com/.*actions|codecov\\.io|coveralls\\.io'

  # Has conventional versioning
  - id: legitimate/conventional-version
    description: Uses conventional version format
    criticality: inert
    confidence: 0.75
    file_types: [packagejson]
    condition:
      type: string
      regex: '"version":\s*"[0-9]+\.[0-9]+\.[0-9]+(?:-(?:alpha|beta|rc|next|canary)\.[0-9]+)?"'

  # Has release/publish workflow scripts
  - id: legitimate/has-release-scripts
    description: Package has release management scripts
    criticality: inert
    confidence: 0.85
    file_types: [packagejson]
    condition:
      type: string
      regex: '"(?:release|publish|version|prepublishOnly|postversion)":'

  # Has changeset or conventional commits tooling
  - id: legitimate/has-changelog-tooling
    description: Package uses changelog/versioning tooling
    criticality: inert
    confidence: 0.9
    file_types: [packagejson]
    condition:
      type: string
      regex: '@changesets/|standard-version|semantic-release|conventional-changelog'

  # Has peer dependency range (well-designed library)
  - id: legitimate/peer-range
    description: Uses version ranges for peer dependencies
    criticality: inert
    confidence: 0.85
    file_types: [packagejson]
    condition:
      type: string
      regex: '"peerDependencies":\s*\{[^}]*"[>=<^~]'

  # Has optional dependencies
  - id: legitimate/has-optional-deps
    description: Package has optional dependencies
    criticality: inert
    confidence: 0.8
    file_types: [packagejson]
    condition:
      type: string
      exact: '"optionalDependencies":'

  # Has cpu/os restrictions
  - id: legitimate/has-platform-restrictions
    description: Package specifies platform restrictions
    criticality: inert
    confidence: 0.85
    file_types: [packagejson]
    condition:
      type: string
      regex: '"cpu":\s*\[|"os":\s*\['

  # Uses scoped name from known org
  - id: legitimate/scoped-known-org
    description: Package from known organization scope
    criticality: inert
    confidence: 0.85
    file_types: [packagejson]
    condition:
      type: string
      regex: '"name":\s*"@(?:types|babel|rollup|webpack|eslint|typescript-eslint|testing-library|storybook|angular|vue|emotion|chakra-ui)/'

  # Has npm scripts that reference node_modules/.bin
  - id: legitimate/uses-bin-scripts
    description: Scripts reference node_modules binaries
    criticality: inert
    confidence: 0.8
    file_types: [packagejson]
    condition:
      type: string
      regex: 'node_modules/\\.bin/|npx |npm run '

  # Has husky/lint-staged (pre-commit tooling)
  - id: legitimate/has-git-hooks
    description: Package uses git hooks tooling
    criticality: inert
    confidence: 0.9
    file_types: [packagejson]
    condition:
      type: string
      regex: '"husky"|"lint-staged"|"pre-commit"|"simple-git-hooks"'

