# C2 Infrastructure Detection - IP Addresses
# Detects hardcoded IP addresses, ports, and obfuscated C2 patterns
# ATT&CK: T1071.001

defaults:
  # IP address strings can appear in any file type
  for: ["*"]
  mbc: "C0002"
  attack: "T1071.001"
  crit: suspicious

traits:
  - id: hardcoded-ipv4
    desc: "Hardcoded IPv4 address"
    conf: 0.8
    if:
      type: content


  # === Port number atomic indicators ===
  - id: port-23
    desc: "Port 23 (telnet)"
    crit: inert
    conf: 0.5
    if:
      type: string
      regex: ":23\\b"

  - id: port-80
    desc: "Port 80 (HTTP)"
    crit: inert
    conf: 0.4
    if:
      type: string
      regex: ":80\\b"

  - id: port-443
    desc: "Port 443 (HTTPS)"
    crit: inert
    conf: 0.4
    if:
      type: string
      regex: ":443\\b"

  - id: port-8080
    desc: "Port 8080 (HTTP alt)"
    crit: inert
    conf: 0.5
    if:
      type: string
      regex: ":8080\\b"

  - id: port-4444
    desc: "Port 4444 (Metasploit default)"
    crit: inert
    conf: 0.6
    if:
      type: string
      regex: ":4444\\b"

  - id: port-1337
    desc: "Port 1337 (leet)"
    crit: inert
    conf: 0.5
    if:
      type: string
      regex: ":1337\\b"

  - id: port-31337
    desc: "Port 31337 (eleet)"
    crit: inert
    conf: 0.6
    if:
      type: string
      regex: ":31337\\b"

composite_rules:
  - id: port-number-constant
    desc: "Common C2 port number (23,"
    crit: notable
    conf: 0.6
    mbc: none
    attack: none
    count_min: 1
    any:
      - id: port-23
      - id: port-80
      - id: port-443
      - id: port-8080
      - id: port-4444
      - id: port-1337
      - id: port-31337

  - id: private-ip-reference
    desc: "Private/internal IP address reference"
    crit: notable
    conf: 0.75
    mbc: none
    attack: none
    count_min: 1
    any:
      - id: private-ip-10
      - id: private-ip-172
      - id: private-ip-192

  - id: obfuscated-address
    desc: "C2 address obfuscation (HTTP client"
    conf: 0.85
    mbc: "B0032"
    attack: "T1027"
    for: [elf]
    all:
      - id: truncated-http-url
    none:
      - id: hardcoded-ipv4

  - id: dynamic-ip
    desc: "Dynamic IP address construction"
    conf: 0.8
    mbc: "B0032"
    attack: "T1027"
    all:
      - id: ip-format-string
    none:
      - id: hardcoded-ipv4
