# C2 Infrastructure Detection - IP Addresses
# Detects hardcoded IP addresses, ports, and obfuscated C2 patterns
# ATT&CK: T1071.001

defaults:
  file_types: [elf, macho, pe]
  mbc: "C0002"
  attack: "T1071.001"
  criticality: suspicious

composite_rules:
  - id: c2/infrastructure/ip/hardcoded-ipv4
    description: "Hardcoded IPv4 address"
    confidence: 0.8
    condition:
      type: string
      # Strict IPv4 regex that:
      # - Rejects leading zeros
      # - Ensures it's not part of a version string (vX.X.X.X) or long numeric string
      # - Each octet: 0-255
      regex: "(?<![0-9./vV])(?:(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])\\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])(?![0-9.])"

  - id: c2/infrastructure/ip/ipv4-with-port
    description: "IPv4 address with port number"
    confidence: 0.9
    condition:
      type: string
      # Strict IPv4:port - no leading zeros in octets, port 1-65535
      regex: "\\b(?:(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])\\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9]):[1-9][0-9]{0,4}\\b"

  - id: c2/infrastructure/ip/http-url-with-ip
    description: "HTTP URL with hardcoded IP address"
    confidence: 0.9
    file_types: [all]  # Override: applies to all file types
    condition:
      type: string
      # HTTP(S) URL with strict IPv4 (no leading zeros)
      regex: "https?://(?:(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])\\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])"

  - id: c2/infrastructure/ip/private-ip-reference
    description: "Private/internal IP address reference"
    criticality: notable
    confidence: 0.75
    mbc: none  # Override: not C2 related
    attack: none
    condition:
      type: yara
      # Use YARA for cleaner private IP detection with proper octet validation
      source: |
        rule private_ipv4 {
          strings:
            // 10.x.x.x - Class A private
            $ten = /\b10\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\b/
            // 172.16-31.x.x - Class B private
            $oneseventwo = /\b172\.(1[6-9]|2[0-9]|3[01])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\b/
            // 192.168.x.x - Class C private
            $onenine = /\b192\.168\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\b/
          condition:
            any of them
        }

  - id: c2/infrastructure/ip/ip-format-string
    description: "IP address format string (dynamic IP construction)"
    criticality: notable
    confidence: 0.7
    mbc: "B0032"
    attack: "T1027"
    condition:
      type: string
      regex: "%[0-9]*h{0,2}[ud]\\.%[0-9]*h{0,2}[ud]"

  - id: c2/infrastructure/ip/truncated-http-url
    description: "Truncated HTTP URL (C2 address likely obfuscated)"
    confidence: 0.85
    mbc: "B0032"
    attack: "T1027"
    file_types: [elf]  # Override: ELF only
    condition:
      type: string
      regex: "wget http://[^0-9a-zA-Z]|curl http://[^0-9a-zA-Z]|http://\\x00"
      search_raw: true

  - id: c2/infrastructure/ip/port-number-constant
    description: "Common C2 port number (23, 80, 443, 8080, 4444)"
    criticality: notable
    confidence: 0.6
    mbc: none  # Override: port alone isn't C2
    attack: none
    condition:
      type: string
      regex: ":(?:23|80|443|8080|4444|1337|31337)\\b"

  - id: c2/infrastructure/obfuscated-address
    description: "C2 address obfuscation (HTTP client + no visible IP)"
    confidence: 0.85
    mbc: "B0032"
    attack: "T1027"
    file_types: [elf]
    requires_all:
      - type: trait
        id: truncated-http-url
    requires_none:
      - type: trait
        id: hardcoded-ipv4

  - id: c2/infrastructure/dynamic-ip
    description: "Dynamic IP address construction"
    confidence: 0.8
    mbc: "B0032"
    attack: "T1027"
    requires_all:
      - type: trait
        id: ip-format-string
    requires_none:
      - type: trait
        id: hardcoded-ipv4
