# Rustfmt configuration for consistent, readable code
# Balances strictness with developer productivity (stable features only)

# Basic formatting
edition = "2021"
max_width = 120  # Slightly wider for better readability
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Function and control flow formatting
fn_params_layout = "Tall"

# Advanced formatting options
use_small_heuristics = "Max"  # More aggressive formatting
merge_derives = true
use_field_init_shorthand = true
use_try_shorthand = true

# Only use stable features to avoid warnings
unstable_features = false