# C2 Infrastructure Detection - Domains
# Detects hardcoded domain names and suspicious TLDs
# ATT&CK: T1071.001

defaults:
  # Domain strings can appear in any file type
  file_types: [*]
  mbc: "C0002"
  attack: "T1071.001"

traits:
  # Atomic traits for composite rules
  - id: hardcoded-domain-com-pattern
    description: "Hardcoded .com/.org/.net domain pattern"
    criticality: notable
    confidence: 0.7
    condition:
      type: yara
      source: |
        rule hardcoded_domain_com {
          meta:
            description = "Detects hardcoded .com/.org/.net domains excluding known legitimate vendors"
          strings:
            // Generic domain pattern
            $domain = /\b[a-zA-Z0-9][-a-zA-Z0-9]{0,62}\.(com|org|net)\b/
            // Known legitimate OS vendor / major software domains (excludes)
            $legit_apple = "apple.com" ascii nocase
            $legit_microsoft = "microsoft.com" ascii nocase
            $legit_windows = "windows.com" ascii nocase
            $legit_google = "google.com" ascii nocase
            $legit_android = "android.com" ascii nocase
            $legit_mozilla = "mozilla.org" ascii nocase
            $legit_gnu = "gnu.org" ascii nocase
            $legit_kernel = "kernel.org" ascii nocase
            $legit_debian = "debian.org" ascii nocase
            $legit_ubuntu = "ubuntu.com" ascii nocase
            $legit_redhat = "redhat.com" ascii nocase
            $legit_fedora = "fedoraproject.org" ascii nocase
            $legit_github = "github.com" ascii nocase
            $legit_gitlab = "gitlab.com" ascii nocase
            $legit_sourceforge = "sourceforge.net" ascii nocase
            $legit_python = "python.org" ascii nocase
            $legit_pypi = "pypi.org" ascii nocase
            $legit_npmjs = "npmjs.com" ascii nocase
            $legit_npmjs_org = "npmjs.org" ascii nocase
            $legit_rubygems = "rubygems.org" ascii nocase
            $legit_rust = "rust-lang.org" ascii nocase
            $legit_golang = "golang.org" ascii nocase
            $legit_cloudflare = "cloudflare.com" ascii nocase
            $legit_amazon = "amazon.com" ascii nocase
            $legit_aws = "amazonaws.com" ascii nocase
            $legit_icloud = "icloud.com" ascii nocase
            $legit_docker = "docker.com" ascii nocase
            $legit_openssl = "openssl.org" ascii nocase
            $legit_curl = "curl.se" ascii nocase
            $legit_ezgif = "ezgif.com" ascii nocase
          condition:
            $domain and not any of ($legit*)
        }

  - id: hardcoded-domain-suspicious-pattern
    description: "Hardcoded suspicious TLD domain pattern"
    criticality: suspicious
    confidence: 0.85
    condition:
      type: string
      # Require subdomain or URL context to avoid matching Apple framework names
      regex: "\\b[a-zA-Z0-9][-a-zA-Z0-9]{0,62}\\.[a-zA-Z0-9][-a-zA-Z0-9]{0,62}\\.(ru|cn|xyz|top|cc|ws|tk|ml|ga|cf|gq|pw|biz|club|date|download|racing|win|party|review|accountant|science|trade|webcam|bid|loan|pro)\\b|https?://[a-zA-Z0-9][-a-zA-Z0-9]*\\.(ru|cn|xyz|top|cc|ws|tk|ml|ga|cf|gq|pw|biz|club|work|date|stream|download|racing|pro)"

  - id: dynamic-dns-domain-pattern
    description: "Dynamic DNS domain pattern"
    criticality: suspicious
    confidence: 0.9
    condition:
      type: string
      regex: "\\b[a-zA-Z0-9][-a-zA-Z0-9]*\\.(duckdns|no-ip|dynu|freedns|afraid|hopto|zapto|sytes|ddns|servebeer|servehttp|serveftp|servegame|servequake|redirectme|bounceme|myftp|myvnc)\\.[a-z]{2,6}\\b"

  - id: http-url-with-domain-pattern
    description: "Network URL with domain name pattern"
    criticality: notable
    confidence: 0.7
    condition:
      type: string
      regex: "(?:https?|wss?)://[a-zA-Z0-9][-a-zA-Z0-9]*\\.[a-zA-Z]{2,6}(?:/|$|:)"
      exclude_patterns:
        # Documentation/standards
        - "ezgif\\.com"
        - "w3\\.org"
        - "schemas\\.microsoft\\.com"
        - "www\\.google\\.com"
        - "googleapis\\.com"
        - "mdn\\.io"
        - "developer\\.mozilla\\.org"
        - "docs\\.github\\.com"
        - "nodejs\\.org"
        - "npmjs\\.com"
        - "npmjs\\.org"
        # CI/CD services
        - "travis-ci\\.org"
        - "travis-ci\\.com"
        - "circleci\\.com"
        - "github\\.com"
        - "gitlab\\.com"
        - "bitbucket\\.org"
        - "codecov\\.io"
        - "coveralls\\.io"
        - "snyk\\.io"
        # Package registries
        - "registry\\.npmjs\\.org"
        - "yarnpkg\\.com"
        - "unpkg\\.com"
        - "jsdelivr\\.net"
        - "cdnjs\\.cloudflare\\.com"
        # Major vendors
        - "apple\\.com"
        - "microsoft\\.com"
        - "amazon\\.com"
        - "aws\\.amazon\\.com"

  - id: url-path-payload-pattern
    description: "URL path suggesting payload download pattern"
    criticality: suspicious
    confidence: 0.8
    attack: "T1105"  # Override: Ingress Tool Transfer
    condition:
      type: string
      regex: "(?:GET|POST|PUT)\\s+/[a-zA-Z0-9_./-]*\\.(bin|exe|sh|elf|dll|so|dat|payload|bot|drop)"

  # === Malicious file hosting domains (atomic) ===
  - id: bullethost-cloud
    description: Bullethost.cloud file hosting
    criticality: inert
    confidence: 0.7
    attack: "T1105"
    condition:
      type: string
      exact: "bullethost.cloud"

  - id: anonfiles-com
    description: Anonfiles.com file hosting
    criticality: inert
    confidence: 0.7
    attack: "T1105"
    condition:
      type: string
      exact: "anonfiles.com"

  - id: gofile-io
    description: Gofile.io file hosting
    criticality: inert
    confidence: 0.7
    attack: "T1105"
    condition:
      type: string
      exact: "gofile.io"

  - id: transfer-sh
    description: Transfer.sh file hosting
    criticality: inert
    confidence: 0.7
    attack: "T1105"
    condition:
      type: string
      exact: "transfer.sh"

  - id: tmpfiles-org
    description: Tmpfiles.org file hosting
    criticality: inert
    confidence: 0.7
    attack: "T1105"
    condition:
      type: string
      exact: "tmpfiles.org"

  - id: catbox-moe
    description: Catbox.moe file hosting
    criticality: inert
    confidence: 0.7
    attack: "T1105"
    condition:
      type: string
      exact: "catbox.moe"

  - id: uguu-se
    description: Uguu.se file hosting
    criticality: inert
    confidence: 0.7
    attack: "T1105"
    condition:
      type: string
      exact: "uguu.se"

  - id: pomf-cat
    description: Pomf.cat file hosting
    criticality: inert
    confidence: 0.7
    attack: "T1105"
    condition:
      type: string
      exact: "pomf.cat"

  - id: 0x0-st
    description: 0x0.st file hosting
    criticality: inert
    confidence: 0.7
    attack: "T1105"
    condition:
      type: string
      exact: "0x0.st"

  - id: file-io
    description: File.io file hosting
    criticality: inert
    confidence: 0.7
    attack: "T1105"
    condition:
      type: string
      exact: "file.io"

  - id: filedropper-com
    description: Filedropper.com file hosting
    criticality: inert
    confidence: 0.7
    attack: "T1105"
    condition:
      type: string
      exact: "filedropper.com"

  # Cloud storage abuse for payload hosting
  - id: appwrite-storage
    description: Appwrite cloud storage (commonly abused for malware payloads)
    criticality: suspicious
    confidence: 0.85
    attack: "T1105"
    condition:
      type: string
      regex: '[a-z0-9-]+\.cloud\.appwrite\.io/v[0-9]+/storage/buckets/[a-z0-9]+/files/'

  - id: supabase-storage
    description: Supabase storage endpoint (can be abused for payloads)
    criticality: notable
    confidence: 0.75
    attack: "T1105"
    condition:
      type: string
      regex: '[a-z0-9]+\.supabase\.co/storage/v[0-9]+/'

  - id: firebase-storage
    description: Firebase storage endpoint (can be abused for payloads)
    criticality: notable
    confidence: 0.7
    attack: "T1105"
    condition:
      type: string
      regex: 'firebasestorage\.googleapis\.com/v[0-9]+/b/[^/]+/o/'

  # === PHP collector scripts (atomic) ===
  - id: php-collect
    description: PHP collect endpoint
    criticality: inert
    confidence: 0.6
    attack: "T1041"
    condition:
      type: string
      regex: '/collect[_-]?(info|data|stats)?\.php'

  - id: php-log
    description: PHP log endpoint
    criticality: inert
    confidence: 0.6
    attack: "T1041"
    condition:
      type: string
      regex: '/log[_-]?(info|data)?\.php'

  - id: php-report
    description: PHP report endpoint
    criticality: inert
    confidence: 0.6
    attack: "T1041"
    condition:
      type: string
      exact: "/report.php"

  - id: php-beacon
    description: PHP beacon endpoint
    criticality: inert
    confidence: 0.6
    attack: "T1041"
    condition:
      type: string
      exact: "/beacon.php"

  - id: php-gate
    description: PHP gate endpoint
    criticality: inert
    confidence: 0.6
    attack: "T1041"
    condition:
      type: string
      exact: "/gate.php"

  # Internal API probing
  - id: internal-api-probe
    description: Probes internal network API endpoints
    criticality: suspicious
    confidence: 0.9
    attack: "T1046"
    file_types: [javascript, typescript]
    condition:
      type: string
      regex: 'http://(internal|localhost|127\.0\.0\.1|10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[01]))[-a-zA-Z0-9.]*/(api|ping|health|status)'

  # Hardcoded IP addresses
  - id: hardcoded-ip
    description: Hardcoded IP address (potential C2)
    criticality: suspicious
    confidence: 0.85
    attack: "T1071"
    condition:
      type: string
      regex: 'https?://\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}[:/]'

  # === Serverless function URLs (atomic) ===
  - id: aws-api-gateway
    description: AWS API Gateway endpoint
    criticality: inert
    confidence: 0.5
    attack: "T1071"
    condition:
      type: string
      regex: 'execute-api\.[a-z0-9-]+\.amazonaws\.com'

  - id: azure-websites
    description: Azure Websites endpoint
    criticality: inert
    confidence: 0.5
    attack: "T1071"
    condition:
      type: string
      regex: '[a-z0-9-]+\.azurewebsites\.net'

  - id: google-cloud-functions
    description: Google Cloud Functions endpoint
    criticality: inert
    confidence: 0.5
    attack: "T1071"
    condition:
      type: string
      regex: '[a-z0-9-]+\.cloudfunctions\.net'

  - id: vercel-app
    description: Vercel app endpoint
    criticality: inert
    confidence: 0.5
    attack: "T1071"
    condition:
      type: string
      regex: '[a-z0-9-]+\.vercel\.app'

  - id: netlify-app
    description: Netlify app endpoint
    criticality: inert
    confidence: 0.5
    attack: "T1071"
    condition:
      type: string
      regex: '[a-z0-9-]+\.netlify\.app'

  # === Ngrok tunnels (atomic) ===
  - id: ngrok-io
    description: Ngrok.io tunnel endpoint
    criticality: inert
    confidence: 0.7
    attack: "T1071"
    condition:
      type: string
      regex: '[a-z0-9]+\.ngrok\.io'

  - id: ngrok-free-app
    description: Ngrok-free.app tunnel endpoint
    criticality: inert
    confidence: 0.7
    attack: "T1071"
    condition:
      type: string
      regex: '[a-z0-9]+\.ngrok-free\.app'

  # === Pastebin-like services (atomic) ===
  - id: pastebin-com
    description: Pastebin.com with path
    criticality: inert
    confidence: 0.6
    attack: "T1102"
    condition:
      type: string
      regex: 'pastebin\.com/[a-zA-Z0-9]+'

  - id: hastebin-com
    description: Hastebin.com with path
    criticality: inert
    confidence: 0.6
    attack: "T1102"
    condition:
      type: string
      regex: 'hastebin\.com/[a-zA-Z0-9]+'

  - id: ghostbin-com
    description: Ghostbin.com with path
    criticality: inert
    confidence: 0.6
    attack: "T1102"
    condition:
      type: string
      regex: 'ghostbin\.com/[a-zA-Z0-9]+'

  - id: paste-ee
    description: Paste.ee with path
    criticality: inert
    confidence: 0.6
    attack: "T1102"
    condition:
      type: string
      regex: 'paste\.ee/[a-zA-Z0-9]+'

  - id: dpaste-com
    description: Dpaste.com with path
    criticality: inert
    confidence: 0.6
    attack: "T1102"
    condition:
      type: string
      regex: 'dpaste\.com/[a-zA-Z0-9]+'

  - id: privatebin-net
    description: Privatebin.net with path
    criticality: inert
    confidence: 0.6
    attack: "T1102"
    condition:
      type: string
      regex: 'privatebin\.net/[a-zA-Z0-9]+'

  - id: rentry-co
    description: Rentry.co with path
    criticality: inert
    confidence: 0.6
    attack: "T1102"
    condition:
      type: string
      regex: 'rentry\.co/[a-zA-Z0-9]+'

  # Vercel serverless C2 (elevated - commonly abused)
  - id: vercel-serverless
    description: Contacts Vercel serverless function (commonly abused for C2)
    criticality: suspicious
    confidence: 0.85
    attack: "T1071"
    condition:
      type: string
      regex: '[a-z0-9-]+\.vercel\.app(?:/|$)'

  # === Replit-hosted (atomic) ===
  - id: replit-dev
    description: Replit.dev endpoint
    criticality: inert
    confidence: 0.6
    attack: "T1071"
    condition:
      type: string
      regex: '[a-z0-9-]+\.replit\.dev'

  - id: repl-co
    description: Repl.co endpoint
    criticality: inert
    confidence: 0.6
    attack: "T1071"
    condition:
      type: string
      regex: '[a-z0-9-]+\.repl\.co'

  # Glitch-hosted C2
  - id: glitch-hosted
    description: Contacts Glitch-hosted endpoint
    criticality: suspicious
    confidence: 0.8
    attack: "T1071"
    condition:
      type: string
      regex: '[a-z0-9-]+\.glitch\.me'

  # Railway-hosted C2
  - id: railway-hosted
    description: Contacts Railway-hosted endpoint
    criticality: notable
    confidence: 0.75
    attack: "T1071"
    condition:
      type: string
      regex: '[a-z0-9-]+\.railway\.app'

  # Render-hosted C2
  - id: render-hosted
    description: Contacts Render-hosted endpoint
    criticality: notable
    confidence: 0.75
    attack: "T1071"
    condition:
      type: string
      regex: '[a-z0-9-]+\.onrender\.com'

  # Heroku-hosted C2
  - id: heroku-hosted
    description: Contacts Heroku-hosted endpoint
    criticality: notable
    confidence: 0.7
    attack: "T1071"
    condition:
      type: string
      regex: '[a-z0-9-]+\.herokuapp\.com'

  # Serveo SSH tunnel
  - id: serveo-tunnel
    description: Serveo SSH tunnel endpoint (reverse shell infrastructure)
    criticality: suspicious
    confidence: 0.95
    attack: "T1572"
    condition:
      type: string
      regex: 'serveo\.net'

  # Localtunnel
  - id: localtunnel
    description: Localtunnel endpoint (reverse shell infrastructure)
    criticality: suspicious
    confidence: 0.85
    attack: "T1572"
    condition:
      type: string
      regex: '[a-z0-9-]+\.loca\.lt'

  # Localhost.run tunnel
  - id: localhost-run
    description: Localhost.run tunnel endpoint
    criticality: suspicious
    confidence: 0.85
    attack: "T1572"
    condition:
      type: string
      regex: '[a-z0-9-]+\.localhost\.run'

  # Cloudflare tunnel
  - id: cloudflare-tunnel
    description: Cloudflare tunnel endpoint
    criticality: notable
    confidence: 0.7
    attack: "T1572"
    condition:
      type: string
      regex: '[a-z0-9-]+\.trycloudflare\.com'

  # === Chisel tunnel (atomic) ===
  - id: chisel-client
    description: Chisel client command
    criticality: inert
    confidence: 0.7
    attack: "T1572"
    condition:
      type: string
      regex: 'chisel\s+client'

  - id: chisel-server
    description: Chisel server command
    criticality: inert
    confidence: 0.7
    attack: "T1572"
    condition:
      type: string
      regex: 'chisel\s+server'

  - id: chisel-github
    description: Chisel GitHub repo reference
    criticality: inert
    confidence: 0.7
    attack: "T1572"
    condition:
      type: string
      exact: "jpillora/chisel"

composite_rules:
  - id: hardcoded-domain-com
    description: "Hardcoded .com domain"
    criticality: notable
    confidence: 0.7
    requires_all:
      - id: hardcoded-domain-com-pattern

  - id: hardcoded-domain-suspicious
    description: "Hardcoded suspicious TLD domain (.ru, .cn, .xyz, .top, .pro)"
    criticality: suspicious
    confidence: 0.85
    requires_all:
      - id: hardcoded-domain-suspicious-pattern

  - id: dynamic-dns-domain
    description: "Dynamic DNS domain (common C2 infrastructure)"
    criticality: suspicious
    confidence: 0.9
    requires_all:
      - id: dynamic-dns-domain-pattern

  - id: http-url-with-domain
    description: "Network URL with domain name"
    criticality: notable
    confidence: 0.7
    requires_all:
      - id: http-url-with-domain-pattern

  - id: url-path-payload
    description: "URL path suggesting payload download"
    criticality: suspicious
    confidence: 0.8
    attack: "T1105"
    requires_all:
      - id: url-path-payload-pattern

  - id: c2-domain
    description: "Likely C2 domain (suspicious TLD or dynamic DNS)"
    criticality: suspicious
    confidence: 0.85
    requires_count: 1
    conditions:
      - id: hardcoded-domain-suspicious-pattern
      - id: dynamic-dns-domain-pattern

  # Malware hosting services
  - id: malware-hosting
    description: Contacts known malware/payload hosting service
    criticality: suspicious
    confidence: 0.95
    attack: "T1105"
    requires_count: 1
    conditions:
      - id: bullethost-cloud
      - id: anonfiles-com
      - id: gofile-io
      - id: transfer-sh
      - id: tmpfiles-org
      - id: catbox-moe
      - id: uguu-se
      - id: pomf-cat
      - id: 0x0-st
      - id: file-io
      - id: filedropper-com

  # PHP collector endpoints
  - id: php-collector
    description: Contacts PHP data collection endpoint
    criticality: suspicious
    confidence: 0.85
    attack: "T1041"
    requires_count: 1
    conditions:
      - id: php-collect
      - id: php-log
      - id: php-report
      - id: php-beacon
      - id: php-gate

  # Serverless function endpoints
  - id: serverless-function
    description: Contacts serverless function endpoint (Lambda, Azure, etc.)
    criticality: notable
    confidence: 0.7
    attack: "T1071"
    requires_count: 1
    conditions:
      - id: aws-api-gateway
      - id: azure-websites
      - id: google-cloud-functions
      - id: vercel-app
      - id: netlify-app

  # Ngrok tunnels
  - id: ngrok-tunnel
    description: Contacts ngrok tunnel endpoint
    criticality: suspicious
    confidence: 0.9
    attack: "T1071"
    requires_count: 1
    conditions:
      - id: ngrok-io
      - id: ngrok-free-app

  # Paste services
  - id: paste-service
    description: Contacts paste/bin service (common payload host)
    criticality: suspicious
    confidence: 0.85
    attack: "T1102"
    requires_count: 1
    conditions:
      - id: pastebin-com
      - id: hastebin-com
      - id: ghostbin-com
      - id: paste-ee
      - id: dpaste-com
      - id: privatebin-net
      - id: rentry-co

  # Replit-hosted
  - id: replit-hosted
    description: Contacts Replit-hosted endpoint (commonly abused)
    criticality: suspicious
    confidence: 0.85
    attack: "T1071"
    requires_count: 1
    conditions:
      - id: replit-dev
      - id: repl-co

  # Chisel tunnel
  - id: chisel-tunnel
    description: Chisel reverse tunnel infrastructure
    criticality: suspicious
    confidence: 0.95
    attack: "T1572"
    requires_count: 1
    conditions:
      - id: chisel-client
      - id: chisel-server
      - id: chisel-github
