# C2 Infrastructure Detection - Domains
# Detects hardcoded domain names and suspicious TLDs
# ATT&CK: T1071.001

defaults:
  file_types: [elf, macho, pe]
  mbc: "C0002"
  attack: "T1071.001"

composite_rules:
  - id: c2/infrastructure/domain/hardcoded-domain-com
    description: "Hardcoded .com domain"
    criticality: notable
    confidence: 0.7
    condition:
      type: string
      regex: "\\b[a-zA-Z0-9][-a-zA-Z0-9]{0,62}\\.(com|org|net)\\b"

  - id: c2/infrastructure/domain/hardcoded-domain-suspicious
    description: "Hardcoded suspicious TLD domain (.ru, .cn, .xyz, .top)"
    criticality: suspicious
    confidence: 0.85
    condition:
      type: string
      # Require subdomain or URL context to avoid matching Apple framework names like
      # "logging.stream", "kernel.work", "acquire.stream", "virtual.stream"
      # Also exclude "work" and "stream" which have many legitimate uses
      regex: "\\b[a-zA-Z0-9][-a-zA-Z0-9]{0,62}\\.[a-zA-Z0-9][-a-zA-Z0-9]{0,62}\\.(ru|cn|xyz|top|cc|ws|tk|ml|ga|cf|gq|pw|biz|club|date|download|racing|win|party|review|accountant|science|trade|webcam|bid|loan)\\b|https?://[a-zA-Z0-9][-a-zA-Z0-9]*\\.(ru|cn|xyz|top|cc|ws|tk|ml|ga|cf|gq|pw|biz|club|work|date|stream|download|racing)"

  - id: c2/infrastructure/domain/dynamic-dns-domain
    description: "Dynamic DNS domain (common C2 infrastructure)"
    criticality: suspicious
    confidence: 0.9
    condition:
      type: string
      regex: "\\b[a-zA-Z0-9][-a-zA-Z0-9]*\\.(duckdns|no-ip|dynu|freedns|afraid|hopto|zapto|sytes|ddns|servebeer|servehttp|serveftp|servegame|servequake|redirectme|bounceme|myftp|myvnc)\\.[a-z]{2,6}\\b"

  - id: c2/infrastructure/domain/http-url-with-domain
    description: "HTTP URL with domain name"
    criticality: notable
    confidence: 0.7
    file_types: [all]  # Override: applies to all file types
    mbc: none          # Override: no specific MBC
    attack: none       # Override: no specific ATT&CK
    condition:
      type: string
      regex: "https?://[a-zA-Z0-9][-a-zA-Z0-9]*\\.[a-zA-Z]{2,6}(?:/|$|:)"

  - id: c2/infrastructure/domain/url-path-payload
    description: "URL path suggesting payload download"
    criticality: suspicious
    confidence: 0.8
    attack: "T1105"  # Override: Ingress Tool Transfer
    condition:
      type: string
      regex: "(?:GET|POST|PUT)\\s+/[a-zA-Z0-9_./-]*\\.(bin|exe|sh|elf|dll|so|dat|payload|bot|drop)"

  - id: c2/infrastructure/c2-domain
    description: "Likely C2 domain (suspicious TLD or dynamic DNS)"
    criticality: suspicious
    confidence: 0.85
    requires_any:
      - type: trait
        id: hardcoded-domain-suspicious
      - type: trait
        id: dynamic-dns-domain
