# C2 Infrastructure Detection - Domains
# Detects hardcoded domain names and suspicious TLDs
# ATT&CK: T1071.001

defaults:
  # Domain strings can appear in any file type
  for: ["*"]
  mbc: "C0002"
  attack: "T1071.001"

traits:
  # === Domain detection ===
  - id: hardcoded-domain-com
    desc: Hardcoded .com/.org/.net domain (excluding known
    crit: inert
    conf: 0.7
    if:
      type: string
      regex: "\\b[a-zA-Z0-9][-a-zA-Z0-9]{0,62}\\.(com|org|net)\\b"
    not:
      # Major vendors
      - "apple.com"
      - "microsoft.com"
      - "google.com"
      - "amazon.com"
      # Dev platforms
      - "github.com"
      - "gitlab.com"
      - "bitbucket.org"
      # Package registries
      - "npmjs.com"
      - "npmjs.org"
      - "python.org"
      - "pypi.org"
      - "golang.org"
      - "rust-lang.org"
      - "crates.io"
      # Infrastructure
      - "amazonaws.com"
      - "cloudflare.com"
      - "docker.com"
      # Linux distros
      - "mozilla.org"
      - "kernel.org"
      - "debian.org"
      - "ubuntu.com"
      - "redhat.com"
      # Documentation
      - "w3.org"
      - "ietf.org"
      - "example.com"
      - "example.org"
      - "example.net"

  - id: hardcoded-domain-suspicious-pattern
    desc: "Hardcoded suspicious TLD domain pattern"
    crit: notable
    conf: 0.85
    if:
      type: string
      # Require subdomain or URL context to avoid matching programming patterns like time.Time.date
      # Removed: .date (matches Go time.Time.date), .pro (too common)
      # Added: .pe (Peru - commonly abused for short URLs), .su (Soviet Union - malware favorite)
      regex: "\\b[a-zA-Z0-9][-a-zA-Z0-9]{0,62}\\.[a-zA-Z0-9][-a-zA-Z0-9]{0,62}\\.(ru|cn|xyz|top|cc|ws|tk|ml|ga|cf|gq|pw|biz|club|download|racing|win|party|review|accountant|science|trade|webcam|bid|loan|pe|su|icu|buzz)\\b|https?://[a-zA-Z0-9][-a-zA-Z0-9]*\\.(ru|cn|xyz|top|cc|ws|tk|ml|ga|cf|gq|pw|biz|club|work|stream|download|racing|pe|su|icu|buzz)"

  - id: short-domain-url-pattern
    desc: "Very short domain in URL"
    crit: notable
    conf: 0.8
    if:
      type: string
      # Match URLs with very short domain names (2-3 characters) - common for malware C2
      regex: "https?://[a-zA-Z0-9]{2,3}\\.[a-zA-Z]{2,4}[/:]"

  - id: dynamic-dns-domain-pattern
    desc: "Dynamic DNS domain pattern"
    crit: notable
    conf: 0.9
    if:
      type: string
      regex: "\\b[a-zA-Z0-9][-a-zA-Z0-9]*\\.(duckdns|no-ip|dynu|freedns|afraid|hopto|zapto|sytes|ddns|servebeer|servehttp|serveftp|servegame|servequake|redirectme|bounceme|myftp|myvnc)\\.[a-z]{2,6}\\b"

  - id: http-url-with-domain-pattern
    desc: "Network URL with domain name"
    crit: notable
    conf: 0.7
    if:
      type: string
      regex: "(?:https?|wss?)://[a-zA-Z0-9][-a-zA-Z0-9]*\\.[a-zA-Z]{2,6}(?:/|$|:)"
      exclude_patterns:
        # Documentation/standards
        - "ezgif\\.com"
        - "w3\\.org"
        - "schemas\\.microsoft\\.com"
        - "www\\.google\\.com"
        - "googleapis\\.com"
        - "mdn\\.io"
        - "developer\\.mozilla\\.org"
        - "docs\\.github\\.com"
        - "nodejs\\.org"
        - "npmjs\\.com"
        - "npmjs\\.org"
        # CI/CD services
        - "travis-ci\\.org"
        - "travis-ci\\.com"
        - "circleci\\.com"
        - "github\\.com"
        - "gitlab\\.com"
        - "bitbucket\\.org"
        - "codecov\\.io"
        - "coveralls\\.io"
        - "snyk\\.io"
        # Package registries
        - "registry\\.npmjs\\.org"
        - "yarnpkg\\.com"
        - "unpkg\\.com"
        - "jsdelivr\\.net"
        - "cdnjs\\.cloudflare\\.com"
        # Major vendors
        - "apple\\.com"
        - "microsoft\\.com"
        - "amazon\\.com"
        - "aws\\.amazon\\.com"
        # LLVM/compiler projects
        - "llvm\\.org"
        - "clang\\.llvm\\.org"
        - "releases\\.llvm\\.org"
        - "apt\\.llvm\\.org"
        # Build/compiler tools
        - "cmake\\.org"
        - "gcc\\.gnu\\.org"
        - "sourceware\\.org"
        - "savannah\\.gnu\\.org"
        # Linux/system tools
        - "kernel\\.org"
        - "freedesktop\\.org"
        - "mesa3d\\.org"
        - "x\\.org"

  - id: url-path-payload-pattern
    desc: "URL path suggesting payload download"
    crit: suspicious
    conf: 0.8
    attack: "T1105" # Override: Ingress Tool Transfer
    if:
      type: string
      regex: "(?:GET|POST|PUT)\\s+/[a-zA-Z0-9_./-]*\\.(bin|exe|sh|elf|dll|so|dat|payload|bot|drop)"

  # === Malicious file hosting domains (atomic) ===
  - id: bullethost-cloud
    desc: Bullethost.cloud file hosting
    crit: inert
    conf: 0.7
    attack: "T1105"
    if:
      type: string
      substr: "bullethost.cloud"

  - id: anonfiles-com
    desc: Anonfiles.com file hosting
    crit: inert
    conf: 0.7
    attack: "T1105"
    if:
      type: string
      substr: "anonfiles.com"

  - id: gofile-io
    desc: Gofile.io file hosting
    crit: inert
    conf: 0.7
    attack: "T1105"
    if:
      type: string
      substr: "gofile.io"

  - id: transfer-sh
    desc: Transfer.sh file hosting
    crit: inert
    conf: 0.7
    attack: "T1105"
    if:
      type: string
      substr: "transfer.sh"

  - id: tmpfiles-org
    desc: Tmpfiles.org file hosting
    crit: inert
    conf: 0.7
    attack: "T1105"
    if:
      type: string
      substr: "tmpfiles.org"

  - id: catbox-moe
    desc: Catbox.moe file hosting
    crit: inert
    conf: 0.7
    attack: "T1105"
    if:
      type: string
      substr: "catbox.moe"

  - id: uguu-se
    desc: Uguu.se file hosting
    crit: inert
    conf: 0.7
    attack: "T1105"
    if:
      type: string
      substr: "uguu.se"

  - id: pomf-cat
    desc: Pomf.cat file hosting
    crit: inert
    conf: 0.7
    attack: "T1105"
    if:
      type: string
      substr: "pomf.cat"

  - id: 0x0-st
    desc: 0x0.st file hosting
    crit: inert
    conf: 0.7
    attack: "T1105"
    if:
      type: string
      substr: "0x0.st"

  - id: file-io
    desc: File.io file hosting
    crit: inert
    conf: 0.7
    attack: "T1105"
    if:
      type: string
      substr: "file.io"

  - id: filedropper-com
    desc: Filedropper.com file hosting
    crit: inert
    conf: 0.7
    attack: "T1105"
    if:
      type: string
      substr: "filedropper.com"

  # Cloud storage abuse for payload hosting
  - id: appwrite-storage
    desc: Appwrite cloud storage (commonly abused
    crit: suspicious
    conf: 0.85
    attack: "T1105"
    if:
      type: string
      regex: '[a-z0-9-]+\.cloud\.appwrite\.io/v[0-9]+/storage/buckets/[a-z0-9]+/files/'

  - id: supabase-storage
    desc: Supabase storage endpoint (can be
    crit: notable
    conf: 0.75
    attack: "T1105"
    if:
      type: string
      regex: '[a-z0-9]+\.supabase\.co/storage/v[0-9]+/'

  - id: firebase-storage
    desc: Firebase storage endpoint (can be
    crit: notable
    conf: 0.7
    attack: "T1105"
    if:
      type: string
      regex: 'firebasestorage\.googleapis\.com/v[0-9]+/b/[^/]+/o/'

  # === PHP collector scripts (atomic) ===
  - id: php-collect
    desc: PHP collect endpoint
    crit: inert
    conf: 0.6
    attack: "T1041"
    if:
      type: string
      regex: '/collect[_-]?(info|data|stats)?\.php'

  - id: php-log
    desc: PHP log endpoint
    crit: inert
    conf: 0.6
    attack: "T1041"
    if:
      type: string
      regex: '/log[_-]?(info|data)?\.php'

  - id: php-report
    desc: PHP report endpoint
    crit: inert
    conf: 0.6
    attack: "T1041"
    if:
      type: string
      substr: "/report.php"

  - id: php-beacon
    desc: PHP beacon endpoint
    crit: inert
    conf: 0.6
    attack: "T1041"
    if:
      type: string
      substr: "/beacon.php"

  - id: php-gate
    desc: PHP gate endpoint
    crit: inert
    conf: 0.6
    attack: "T1041"
    if:
      type: string
      substr: "/gate.php"

  # Internal API probing
  - id: internal-api-probe
    desc: Probes internal network API endpoints
    crit: suspicious
    conf: 0.9
    attack: "T1046"
    for: [javascript, typescript]
    if:
      type: string
      regex: 'http://(internal|localhost|127\.0\.0\.1|10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[01]))[-a-zA-Z0-9.]*/(api|ping|health|status)'

  # === Serverless function URLs (atomic) ===
  - id: aws-api-gateway
    desc: AWS API Gateway endpoint
    crit: inert
    conf: 0.5
    attack: "T1071"
    if:
      type: string
      regex: 'execute-api\.[a-z0-9-]+\.amazonaws\.com'

  - id: azure-websites
    desc: Azure Websites endpoint
    crit: inert
    conf: 0.5
    attack: "T1071"
    if:
      type: string
      regex: '[a-z0-9-]+\.azurewebsites\.net'

  - id: google-cloud-functions
    desc: Google Cloud Functions endpoint
    crit: inert
    conf: 0.5
    attack: "T1071"
    if:
      type: string
      regex: '[a-z0-9-]+\.cloudfunctions\.net'

  - id: vercel-app
    desc: Vercel app endpoint
    crit: inert
    conf: 0.5
    attack: "T1071"
    if:
      type: string
      regex: '[a-z0-9-]+\.vercel\.app'

  - id: netlify-app
    desc: Netlify app endpoint
    crit: inert
    conf: 0.5
    attack: "T1071"
    if:
      type: string
      regex: '[a-z0-9-]+\.netlify\.app'

  # === Ngrok tunnels (atomic) ===
  - id: ngrok-io
    desc: Ngrok.io tunnel endpoint
    crit: inert
    conf: 0.7
    attack: "T1071"
    if:
      type: string
      regex: '[a-z0-9]+\.ngrok\.io'

  - id: ngrok-free-app
    desc: Ngrok-free.app tunnel endpoint
    crit: inert
    conf: 0.7
    attack: "T1071"
    if:
      type: string
      regex: '[a-z0-9]+\.ngrok-free\.app'

  # === Pastebin-like services (atomic) ===
  - id: pastebin-com
    desc: Pastebin.com with path
    crit: inert
    conf: 0.6
    attack: "T1102"
    if:
      type: string
      regex: 'pastebin\.com/[a-zA-Z0-9]+'

  - id: hastebin-com
    desc: Hastebin.com with path
    crit: inert
    conf: 0.6
    attack: "T1102"
    if:
      type: string
      regex: 'hastebin\.com/[a-zA-Z0-9]+'

  - id: ghostbin-com
    desc: Ghostbin.com with path
    crit: inert
    conf: 0.6
    attack: "T1102"
    if:
      type: string
      regex: 'ghostbin\.com/[a-zA-Z0-9]+'

  - id: paste-ee
    desc: Paste.ee with path
    crit: inert
    conf: 0.6
    attack: "T1102"
    if:
      type: string
      regex: 'paste\.ee/[a-zA-Z0-9]+'

  - id: dpaste-com
    desc: Dpaste.com with path
    crit: inert
    conf: 0.6
    attack: "T1102"
    if:
      type: string
      regex: 'dpaste\.com/[a-zA-Z0-9]+'

  - id: privatebin-net
    desc: Privatebin.net with path
    crit: inert
    conf: 0.6
    attack: "T1102"
    if:
      type: string
      regex: 'privatebin\.net/[a-zA-Z0-9]+'

  - id: rentry-co
    desc: Rentry.co with path
    crit: inert
    conf: 0.6
    attack: "T1102"
    if:
      type: string
      regex: 'rentry\.co/[a-zA-Z0-9]+'

  # Vercel serverless C2 (elevated - commonly abused)
  - id: vercel-serverless
    desc: Contacts Vercel serverless function (commonly
    crit: suspicious
    conf: 0.85
    attack: "T1071"
    if:
      type: string
      regex: '[a-z0-9-]+\.vercel\.app(?:/|$)'

  # === Replit-hosted (atomic) ===
  - id: replit-dev
    desc: Replit.dev endpoint
    crit: inert
    conf: 0.6
    attack: "T1071"
    if:
      type: string
      regex: '[a-z0-9-]+\.replit\.dev'

  - id: repl-co
    desc: Repl.co endpoint
    crit: inert
    conf: 0.6
    attack: "T1071"
    if:
      type: string
      regex: '[a-z0-9-]+\.repl\.co'

  # Glitch-hosted C2
  - id: glitch-hosted
    desc: Contacts Glitch-hosted endpoint
    crit: suspicious
    conf: 0.8
    attack: "T1071"
    if:
      type: string
      regex: '[a-z0-9-]+\.glitch\.me'

  # Railway-hosted C2
  - id: railway-hosted
    desc: Contacts Railway-hosted endpoint
    crit: notable
    conf: 0.75
    attack: "T1071"
    if:
      type: string
      regex: '[a-z0-9-]+\.railway\.app'

  # Render-hosted C2
  - id: render-hosted
    desc: Contacts Render-hosted endpoint
    crit: notable
    conf: 0.75
    attack: "T1071"
    if:
      type: string
      regex: '[a-z0-9-]+\.onrender\.com'

  # Heroku-hosted C2
  - id: heroku-hosted
    desc: Contacts Heroku-hosted endpoint
    crit: notable
    conf: 0.7
    attack: "T1071"
    if:
      type: string
      regex: '[a-z0-9-]+\.herokuapp\.com'

  # Serveo SSH tunnel
  - id: serveo-tunnel
    desc: Serveo SSH tunnel endpoint (reverse
    crit: suspicious
    conf: 0.95
    attack: "T1572"
    if:
      type: string
      regex: 'serveo\.net'

  # Localtunnel
  - id: localtunnel
    desc: Localtunnel endpoint (reverse shell infrastructure)
    crit: suspicious
    conf: 0.85
    attack: "T1572"
    if:
      type: string
      regex: '[a-z0-9-]+\.loca\.lt'

  # Localhost.run tunnel
  - id: localhost-run
    desc: Localhost.run tunnel endpoint
    crit: suspicious
    conf: 0.85
    attack: "T1572"
    if:
      type: string
      regex: '[a-z0-9-]+\.localhost\.run'

  # Cloudflare tunnel
  - id: cloudflare-tunnel
    desc: Cloudflare tunnel endpoint
    crit: notable
    conf: 0.7
    attack: "T1572"
    if:
      type: string
      regex: '[a-z0-9-]+\.trycloudflare\.com'

  # === Chisel tunnel (atomic) ===
  - id: chisel-client
    desc: Chisel client command
    crit: inert
    conf: 0.7
    attack: "T1572"
    if:
      type: string
      regex: 'chisel\s+client'

  - id: chisel-server
    desc: Chisel server command
    crit: inert
    conf: 0.7
    attack: "T1572"
    if:
      type: string
      regex: 'chisel\s+server'

  - id: chisel-github
    desc: Chisel GitHub repo reference
    crit: inert
    conf: 0.7
    attack: "T1572"
    if:
      type: string
      substr: "jpillora/chisel"

composite_rules:
  - id: c2-domain
    desc: "Likely C2 domain (suspicious TLD"
    crit: notable
    conf: 0.85
    count_min: 1
    any:
      - id: hardcoded-domain-suspicious-pattern
      - id: dynamic-dns-domain-pattern

  # Malware hosting services
  - id: malware-hosting
    desc: Contacts known malware/payload hosting service
    crit: suspicious
    conf: 0.95
    attack: "T1105"
    count_min: 1
    any:
      - id: bullethost-cloud
      - id: anonfiles-com
      - id: gofile-io
      - id: transfer-sh
      - id: tmpfiles-org
      - id: catbox-moe
      - id: uguu-se
      - id: pomf-cat
      - id: 0x0-st
      - id: file-io
      - id: filedropper-com

  # PHP collector endpoints
  - id: php-collector
    desc: Contacts PHP data collection endpoint
    crit: suspicious
    conf: 0.85
    attack: "T1041"
    count_min: 1
    any:
      - id: php-collect
      - id: php-log
      - id: php-report
      - id: php-beacon
      - id: php-gate

  # Serverless function endpoints
  - id: serverless-function
    desc: Contacts serverless function endpoint (Lambda,
    crit: notable
    conf: 0.7
    attack: "T1071"
    count_min: 1
    any:
      - id: aws-api-gateway
      - id: azure-websites
      - id: google-cloud-functions
      - id: vercel-app
      - id: netlify-app

  # Ngrok tunnels
  - id: ngrok-tunnel
    desc: Contacts ngrok tunnel endpoint
    crit: suspicious
    conf: 0.9
    attack: "T1071"
    count_min: 1
    any:
      - id: ngrok-io
      - id: ngrok-free-app

  # Paste services
  - id: paste-service
    desc: Contacts paste/bin service (common payload
    crit: suspicious
    conf: 0.85
    attack: "T1102"
    count_min: 1
    any:
      - id: pastebin-com
      - id: hastebin-com
      - id: ghostbin-com
      - id: paste-ee
      - id: dpaste-com
      - id: privatebin-net
      - id: rentry-co

  # Replit-hosted
  - id: replit-hosted
    desc: Contacts Replit-hosted endpoint (commonly abused)
    crit: suspicious
    conf: 0.85
    attack: "T1071"
    count_min: 1
    any:
      - id: replit-dev
      - id: repl-co

  # Chisel tunnel
  - id: chisel-tunnel
    desc: Chisel reverse tunnel infrastructure
    crit: suspicious
    conf: 0.95
    attack: "T1572"
    count_min: 1
    any:
      - id: chisel-client
      - id: chisel-server
      - id: chisel-github
