# Cloud-based Payload Staging Infrastructure Detection
# Detects use of cloud storage services for payload staging/C2
# MBC: B0030 (C2 Communication), T1102 (Web Service)
# ATT&CK: T1102.002 (Bidirectional Communication), T1583 (Acquire Infrastructure)

defaults:
  for: [elf, macho, pe]
  mbc: "B0030"
  attack: "T1102.002"

traits:
  # AWS S3 URL - suspicious bucket names or disguised file extensions
  # Pattern: random/suspicious bucket name + image/doc extension (payload disguise)
  - id: aws-s3-url
    desc: AWS S3 storage URL
    crit: notable
    conf: 0.85
    if:
      type: string
      regex: 'https?://[a-z0-9-]+\.s3(\.[a-z0-9-]+)?\.amazonaws\.com/'
    not:
      # Common legitimate services
      - regex: 'github-production'
      - regex: 'aws-codedeploy'
      - regex: 'elasticbeanstalk'

  # AWS S3 with disguised payload extension (image/doc hiding executable)
  - id: aws-s3-disguised-payload
    desc: AWS S3 disguised payload
    crit: suspicious
    conf: 0.9
    if:
      type: string
      regex: 'https?://[a-z0-9-]+\.s3[^/]*\.amazonaws\.com/[^"\s]+\.(png|jpg|jpeg|gif|ico|bmp|pdf|doc|docx|txt)$'

  # Azure Blob storage URL
  - id: azure-blob-url
    desc: Azure Blob storage URL
    crit: notable
    conf: 0.85
    if:
      type: string
      regex: 'https?://[a-z0-9-]+\.blob\.core\.windows\.net/'

  # Google Cloud Storage URL
  - id: gcs-url
    desc: Google Cloud Storage URL
    crit: notable
    conf: 0.85
    if:
      type: string
      regex: 'https?://storage\.googleapis\.com/[a-z0-9-_]+/'

  # DigitalOcean Spaces URL
  - id: do-spaces-url
    desc: DigitalOcean Spaces URL
    crit: notable
    conf: 0.85
    if:
      type: string
      regex: 'https?://[a-z0-9-]+\.[a-z0-9-]+\.digitaloceanspaces\.com/'

  # Cloudflare R2 URL
  - id: cloudflare-r2-url
    desc: Cloudflare R2 storage URL
    crit: notable
    conf: 0.85
    if:
      type: string
      regex: 'https?://[a-z0-9-]+\.r2\.cloudflarestorage\.com/'

  # Backblaze B2 URL
  - id: backblaze-b2-url
    desc: Backblaze B2 storage URL
    crit: notable
    conf: 0.85
    if:
      type: string
      regex: 'https?://[a-z0-9-]+\.backblazeb2\.com/'

  # Rust HTTP client (ureq crate) - indicator of Rust downloader
  - id: rust-ureq-http-client
    desc: Rust ureq HTTP client library
    crit: notable
    conf: 0.9
    if:
      type: string
      regex: '/ureq-[0-9.]+/src/'

  # Rust TLS client (rustls crate) - indicator of Rust HTTPS
  - id: rust-rustls-tls
    desc: Rust rustls TLS library
    crit: notable
    conf: 0.9
    if:
      type: string
      regex: '/rustls-[0-9.]+/src/'

composite_rules:
  # Cloud storage-based dropper/stager
  # Uses cloud storage for payload hosting + HTTP client + self-discovery
  # Complexity: all(3) + any(1) + for(1) = 5 >= 4 HOSTILE
  - id: cloud-payload-dropper
    desc: Cloud storage payload dropper
    crit: hostile
    conf: 0.95
    mbc: "B0030"
    attack: "T1105"
    for: [elf, macho, pe]
    all:
      - id: aws-s3-disguised-payload
      - id: cap/fs/proc/process::process-pid-exe
      - id: cap/crypto/symmetric/stream::chacha-salsa-constant
    any:
      - id: rust-ureq-http-client
      - id: rust-rustls-tls

  # Rust-based cloud downloader/stager
  # Complexity: all(4) + for(1) = 5 >= 4 HOSTILE
  - id: rust-cloud-stager
    desc: Rust cloud storage stager
    crit: hostile
    conf: 0.92
    mbc: "B0030"
    attack: "T1105"
    for: [elf, macho, pe]
    all:
      - id: rust-ureq-http-client
      - id: rust-rustls-tls
      - id: cap/fs/proc/process::process-pid-exe
      - id: aws-s3-disguised-payload

  # Generic cloud-hosted payload with crypto capability
  # Complexity: all(3) + any(1) + for(1) = 5 >= 4 HOSTILE
  - id: cloud-crypto-implant
    desc: Cloud-hosted crypto implant
    crit: hostile
    conf: 0.9
    mbc: "B0030"
    for: [elf, macho, pe]
    all:
      - id: cap/crypto/symmetric/stream::chacha-salsa-constant
      - id: cap/fs/proc/process::process-pid-exe
    any:
      - id: aws-s3-disguised-payload
      - id: azure-blob-url
      - id: gcs-url
      - id: do-spaces-url
