# Default Credential Detection
# Common default passwords used in brute-force attacks
# ATT&CK: T1110.001 (Brute Force: Password Guessing)

traits:
  - id: admin-password
    description: "Default credential: admin variations"
    criticality: notable
    confidence: 0.6
    attack: "T1110.001"
    file_types: [elf]
    condition:
      type: string
      regex: "\\badmin\\b"
      min_count: 3

  - id: root-password
    description: "Default credential: root variations"
    criticality: notable
    confidence: 0.6
    attack: "T1110.001"
    file_types: [elf]
    condition:
      type: string
      regex: "\\broot\\b"
      min_count: 3

  - id: numeric-123456
    description: "Default credential: 123456"
    criticality: suspicious
    confidence: 0.8
    attack: "T1110.001"
    file_types: [elf]
    condition:
      type: string
      # Avoid matching ASCII character tables (0123456789...)
      # Require 123456 not preceded by 0-5 and not followed by 7-9
      regex: "(?<![0-5])123456(?![7-9])"

  # NOTE: "password" alone is too common (system utilities, config, etc.)
  # Real credential brute-force detection requires multiple indicators
  - id: literal-password
    description: "Default credential: password"
    criticality: notable
    confidence: 0.4
    attack: "T1110.001"
    file_types: [elf]
    condition:
      type: string
      exact: "password"

  - id: admin123
    description: "Default credential: admin123"
    criticality: suspicious
    confidence: 0.85
    attack: "T1110.001"
    file_types: [elf]
    condition:
      type: string
      exact: "admin123"

  - id: literal-default
    description: "Default credential: default"
    criticality: notable
    confidence: 0.5
    attack: "T1110.001"
    file_types: [elf]
    condition:
      type: string
      # Word "default" alone is common - require it with control char prefix
      # which suggests credential list with delimiters
      regex: "[\\x00-\\x1f]default[\\x00-\\x1f]?"

  # NOTE: "support" alone is extremely common in system utilities and config
  # Removed as standalone trait - only relevant in composite credential dictionary
  # - id: credential/brute-force/password/support

  - id: guest
    description: "Default credential: guest"
    criticality: notable
    confidence: 0.7
    attack: "T1110.001"
    file_types: [elf]
    condition:
      type: string
      exact: "guest"

  - id: iot-vizxv
    description: "Default IoT credential: vizxv (Dahua)"
    criticality: suspicious
    confidence: 0.95
    attack: "T1110.001"
    file_types: [elf]
    condition:
      type: string
      exact: "vizxv"

  - id: iot-zte
    description: "Default IoT credential: Zte521 (ZTE router)"
    criticality: suspicious
    confidence: 0.95
    attack: "T1110.001"
    file_types: [elf]
    condition:
      type: string
      regex: "[ZP]te?521|Pon521|Zxic521"

  - id: iot-oelinux
    description: "Default IoT credential: oelinux123"
    criticality: suspicious
    confidence: 0.95
    attack: "T1110.001"
    file_types: [elf]
    condition:
      type: string
      exact: "oelinux123"

  - id: iot-xc35
    description: "Default IoT credential: xc3511 (Hikvision)"
    criticality: suspicious
    confidence: 0.95
    attack: "T1110.001"
    file_types: [elf]
    condition:
      type: string
      exact: "xc3511"

  - id: telnet-combo
    description: "Telnet username:password combo format"
    criticality: suspicious
    confidence: 0.8
    attack: "T1110.001"
    file_types: [elf]
    condition:
      type: string
      regex: "\\b(root|admin|user|guest|support):(root|admin|[a-zA-Z0-9]{4,12})\\b"

composite_rules:
  - id: dictionary
    description: "Embedded credential brute-force dictionary"
    criticality: suspicious
    confidence: 0.9
    mbc: "E1040"
    attack: "T1110.001"
    file_types: [elf]
    requires_count: 4
    conditions:
      - id: admin-password
      - id: root-password
      - id: numeric-123456
      - id: literal-password
      - id: admin123
      - id: literal-default
