defaults:
  for:
  - '*'
  mbc: C0002
  attack: T1071.001
traits:
- id: iplogger-domain
  desc: iplogger.org malicious domain
  crit: suspicious
  conf: 1.0
  attack: T1105
  if:
    type: string
    substr: iplogger.org
- id: evilpacket-net
  desc: Evilpacket.net malicious domain
  crit: suspicious
  conf: 1.0
  attack: T1071.001
  if:
    type: string
    substr: evilpacket.net
- id: healdsburgdistricthospital-net
  desc: healdsburgdistricthospital.net malicious domain (Nemucod)
  crit: suspicious
  conf: 1.0
  attack: T1071.001
  if:
    type: string
    substr: healdsburgdistricthospital.net
- id: filioruters-com
  desc: filioruters.com malicious domain
  crit: suspicious
  conf: 1.0
  attack: T1105
  if:
    type: string
    substr: filioruters.com
- id: anti-theft-web-heroku
  desc: Anti-theft-web.herokuapp.com malicious domain (phpass malware)
  crit: suspicious
  conf: 1.0
  attack: T1071.001
  if:
    type: string
    substr: anti-theft-web.herokuapp.com
- id: hardcoded-domain-com
  desc: Hardcoded .com/.org/.net domain (excluding known vendors)
  crit: notable
  conf: 0.7
  if:
    type: string
    regex: \b[a-zA-Z0-9][-a-zA-Z0-9]{0,62}\.(com|org|net)\b
  not:
  - substr: apple.com
  - substr: microsoft.com
  - substr: google.com
  - substr: amazon.com
  - substr: github.com
  - substr: gitlab.com
  - substr: npmjs.com
  - substr: pypi.org
  - substr: python.org
  - substr: rust-lang.org
  - substr: llvm.org
  - substr: kernel.org
  - substr: gnu.org
  - substr: w3.org
  - substr: mozilla.org
  - substr: nodejs.org
  - substr: sourceforge.net
  - substr: freedesktop.org
  - substr: proxy.com
  - substr: example.com
  - substr: example.org
  - substr: xiph.org
  - substr: translationproject.org
  - substr: sourceware.org
  - substr: sage.com
- id: short-domain-url-pattern
  desc: Very short domain in URL
  crit: notable
  conf: 0.8
  if:
    type: string
    regex: https?://[a-zA-Z0-9]{2,3}\.[a-zA-Z]{2,4}[/:]
- id: http-url-binary
  desc: Network URL with domain name (binary)
  crit: notable
  conf: 0.7
  for:
  - binaries
  size_max: 1000000
  if:
    type: string
    regex: (?:https?|wss?)://[a-zA-Z0-9][-a-zA-Z0-9]*\.[a-zA-Z]{2,6}(?:[/?#]|$|:)
    exclude_patterns:
    - ezgif\.com
    - w3\.org
    - schemas\.microsoft\.com
    - www\.google\.com
    - googleapis\.com
    - mdn\.io
    - developer\.mozilla\.org
    - docs\.github\.com
    - docs\.rs
    - docs\.python\.org
    - nodejs\.org
    - npmjs\.com
    - npmjs\.org
    - pypi\.org
    - python\.org
    - rust-lang\.org
    - crates\.io
    - travis-ci\.org
    - travis-ci\.com
    - circleci\.com
    - github\.com
    - gitlab\.com
    - bitbucket\.org
    - codecov\.io
    - coveralls\.io
    - snyk\.io
    - registry\.npmjs\.org
    - yarnpkg\.com
    - unpkg\.com
    - jsdelivr\.net
    - cdnjs\.cloudflare\.com
    - apple\.com
    - microsoft\.com
    - amazon\.com
    - aws\.amazon\.com
    - google\.com
    - sourceforge\.net
    - llvm\.org
    - clang\.llvm\.org
    - releases\.llvm\.org
    - apt\.llvm\.org
    - sqlite\.org
    - cmake\.org
    - gcc\.gnu\.org
    - gnu\.org
    - sourceware\.org
    - savannah\.gnu\.org
    - kernel\.org
    - freedesktop\.org
    - mesa3d\.org
    - x\.org
    - xiph\.org
    - translationproject\.org
    - sourceware\.org
- id: http-url-script
  desc: Network URL with domain name (script)
  crit: notable
  conf: 0.7
  for:
  - scripts
  if:
    type: string
    regex: (?:https?|wss?)://(?:[a-zA-Z0-9][-a-zA-Z0-9]*\.){1,6}[a-zA-Z]{2,6}(?:/|$|:)
    exclude_patterns:
    - ezgif\.com
    - w3\.org
    - schemas\.microsoft\.com
    - www\.google\.com
    - googleapis\.com
    - mdn\.io
    - developer\.mozilla\.org
    - docs\.github\.com
    - docs\.rs
    - docs\.python\.org
    - nodejs\.org
    - npmjs\.com
    - npmjs\.org
    - pypi\.org
    - python\.org
    - rust-lang\.org
    - crates\.io
    - travis-ci\.org
    - travis-ci\.com
    - circleci\.com
    - github\.com
    - gitlab\.com
    - bitbucket\.org
    - codecov\.io
    - coveralls\.io
    - snyk\.io
    - registry\.npmjs\.org
    - yarnpkg\.com
    - unpkg\.com
    - jsdelivr\.net
    - cdnjs\.cloudflare\.com
    - apple\.com
    - microsoft\.com
    - amazon\.com
    - aws\.amazon\.com
    - google\.com
    - sourceforge\.net
    - llvm\.org
    - clang\.llvm\.org
    - releases\.llvm\.org
    - apt\.llvm\.org
    - sqlite\.org
    - cmake\.org
    - gcc\.gnu\.org
    - gnu\.org
    - sourceware\.org
    - savannah\.gnu\.org
    - kernel\.org
    - freedesktop\.org
    - mesa3d\.org
    - x\.org
    - xiph\.org
    - translationproject\.org
    - sourceware\.org
- id: bullethost-cloud
  desc: Bullethost.cloud file hosting
  crit: notable
  conf: 0.7
  attack: T1105
  if:
    type: string
    substr: bullethost.cloud
- id: anonfiles-com
  desc: Anonfiles.com file hosting
  crit: notable
  conf: 0.7
  attack: T1105
  if:
    type: string
    substr: anonfiles.com
- id: gofile-io
  desc: Gofile.io file hosting
  crit: notable
  conf: 0.7
  attack: T1105
  if:
    type: string
    substr: gofile.io
- id: transfer-sh
  desc: Transfer.sh file hosting
  crit: notable
  conf: 0.7
  attack: T1105
  if:
    type: string
    substr: transfer.sh
- id: tmpfiles-org
  desc: Tmpfiles.org file hosting
  crit: notable
  conf: 0.7
  attack: T1105
  if:
    type: string
    substr: tmpfiles.org
- id: catbox-moe
  desc: Catbox.moe file hosting
  crit: notable
  conf: 0.7
  attack: T1105
  if:
    type: string
    substr: catbox.moe
- id: uguu-se
  desc: Uguu.se file hosting
  crit: notable
  conf: 0.7
  attack: T1105
  if:
    type: string
    substr: uguu.se
- id: pomf-cat
  desc: Pomf.cat file hosting
  crit: notable
  conf: 0.7
  attack: T1105
  if:
    type: string
    substr: pomf.cat
- id: 0x0-st
  desc: 0x0.st file hosting
  crit: notable
  conf: 0.7
  attack: T1105
  if:
    type: string
    substr: 0x0.st
- id: file-io
  desc: File.io file hosting
  crit: notable
  conf: 0.7
  attack: T1105
  if:
    type: string
    substr: file.io
- id: filedropper-com
  desc: Filedropper.com file hosting
  crit: notable
  conf: 0.7
  attack: T1105
  if:
    type: string
    substr: filedropper.com
- id: doko-moe
  desc: Doko.moe file hosting (commonly abused)
  crit: notable
  conf: 0.7
  attack: T1105
  if:
    type: string
    substr: doko.moe
- id: openclaw-c2-ip
  desc: OpenClaw C2 IP address
  crit: suspicious
  conf: 1.0
  attack: T1071.001
  if:
    type: string
    substr: 91.92.242.30
- id: openclaw-c2-domain
  desc: OpenClaw C2 domain
  crit: suspicious
  conf: 1.0
  attack: T1071.001
  if:
    type: string
    substr: setup-service.com
- id: appwrite-storage
  desc: Appwrite cloud storage (commonly abused)
  crit: suspicious
  conf: 0.85
  attack: T1105
  if:
    type: string
    regex: '[a-z0-9-]+\.cloud\.appwrite\.io/v[0-9]+/storage/buckets/[a-z0-9]+/files/'
- id: supabase-storage
  desc: Supabase storage endpoint (can be abused)
  crit: notable
  conf: 0.75
  attack: T1105
  if:
    type: string
    regex: '[a-z0-9]+\.supabase\.co/storage/v[0-9]+/'
- id: firebase-storage
  desc: Firebase storage endpoint (can be abused)
  crit: notable
  conf: 0.7
  attack: T1105
  if:
    type: string
    regex: firebasestorage\.googleapis\.com/v[0-9]+/b/[^/]{1,120}/o/
- id: php-collect
  desc: PHP collect endpoint
  crit: suspicious
  conf: 0.6
  attack: T1041
  if:
    type: string
    regex: /collect[_-]?(info|data|stats)?\.php
- id: php-log
  desc: PHP log endpoint
  crit: suspicious
  conf: 0.6
  attack: T1041
  if:
    type: string
    regex: /log[_-]?(info|data)?\.php
- id: php-report
  desc: PHP report endpoint
  crit: suspicious
  conf: 0.6
  attack: T1041
  if:
    type: string
    substr: /report.php
- id: php-beacon
  desc: PHP beacon endpoint
  crit: suspicious
  conf: 0.6
  attack: T1041
  if:
    type: string
    substr: /beacon.php
- id: php-gate
  desc: PHP gate endpoint
  crit: suspicious
  conf: 0.6
  attack: T1041
  if:
    type: string
    substr: /gate.php
- id: php-url
  desc: PHP URL endpoint (often used for C2)
  crit: suspicious
  conf: 0.75
  attack: T1071
  for:
  - shell
  - python
  - ruby
  - javascript
  - perl
  - go
  - rust
  - c
  - cpp
  - java
  - csharp
  - elf
  - macho
  - pe
  - typescript
  if:
    type: string
    regex: https?://[a-zA-Z0-9][-a-zA-Z0-9.]{1,120}(?::[0-9]+)?/.{0,220}\.php(?:[?#]|$)
    exclude_patterns:
    - (?i)sourceforge\.net
    - (?i)vim\.org
    - (?i)docs\.
    - (?i)pypi\.org
    - (?i)npmjs\.com
    - (?i)github\.com
- id: aws-api-gateway
  desc: AWS API Gateway endpoint
  crit: notable
  conf: 0.5
  attack: T1071
  if:
    type: string
    regex: execute-api\.[a-z0-9-]+\.amazonaws\.com
- id: azure-websites
  desc: Azure Websites endpoint
  crit: notable
  conf: 0.5
  attack: T1071
  if:
    type: string
    regex: '[a-z0-9-]+\.azurewebsites\.net'
- id: google-cloud-functions
  desc: Google Cloud Functions endpoint
  crit: notable
  conf: 0.5
  attack: T1071
  if:
    type: string
    regex: '[a-z0-9-]+\.cloudfunctions\.net'
- id: vercel-app
  desc: Vercel app endpoint
  crit: notable
  conf: 0.5
  attack: T1071
  if:
    type: string
    regex: '[a-z0-9-]+\.vercel\.app'
- id: netlify-app
  desc: Netlify app endpoint
  crit: notable
  conf: 0.5
  attack: T1071
  if:
    type: string
    regex: '[a-z0-9-]+\.netlify\.app'
- id: ngrok-io
  desc: Ngrok.io tunnel endpoint
  crit: notable
  conf: 0.7
  attack: T1071
  if:
    type: string
    regex: '[a-z0-9]+\.ngrok\.io'
- id: ngrok-free-app
  desc: Ngrok-free.app tunnel endpoint
  crit: notable
  conf: 0.7
  attack: T1071
  if:
    type: string
    regex: '[a-z0-9]+\.ngrok-free\.app'
- id: pastebin-com
  desc: Pastebin.com with path
  crit: notable
  conf: 0.6
  attack: T1102
  if:
    type: string
    regex: pastebin\.com/[a-zA-Z0-9]+
- id: hastebin-com
  desc: Hastebin.com with path
  crit: notable
  conf: 0.6
  attack: T1102
  if:
    type: string
    regex: hastebin\.com/[a-zA-Z0-9]+
- id: ghostbin-com
  desc: Ghostbin.com with path
  crit: notable
  conf: 0.6
  attack: T1102
  if:
    type: string
    regex: ghostbin\.com/[a-zA-Z0-9]+
- id: paste-ee
  desc: Paste.ee with path
  crit: notable
  conf: 0.6
  attack: T1102
  if:
    type: string
    regex: paste\.ee/[a-zA-Z0-9]+
- id: dpaste-com
  desc: Dpaste.com with path
  crit: notable
  conf: 0.6
  attack: T1102
  if:
    type: string
    regex: dpaste\.com/[a-zA-Z0-9]+
- id: privatebin-net
  desc: Privatebin.net with path
  crit: notable
  conf: 0.6
  attack: T1102
  if:
    type: string
    regex: privatebin\.net/[a-zA-Z0-9]+
- id: rentry-co
  desc: Rentry.co with path
  crit: notable
  conf: 0.6
  attack: T1102
  if:
    type: string
    regex: rentry\.co/[a-zA-Z0-9]+
- id: vercel-serverless
  desc: Contacts Vercel serverless function (commonly abused)
  crit: suspicious
  conf: 0.85
  attack: T1071
  if:
    type: string
    regex: '[a-z0-9-]+\.vercel\.app(?:/|$)'
- id: replit-dev
  desc: Replit.dev endpoint
  crit: notable
  conf: 0.6
  attack: T1071
  if:
    type: string
    regex: (?:[a-z0-9-]{1,63}\.){1,6}replit\.dev
- id: repl-co
  desc: Repl.co endpoint
  crit: notable
  conf: 0.6
  attack: T1071
  if:
    type: string
    regex: (?:[a-z0-9-]{1,63}\.){1,6}repl\.co
- id: replit-id-domain
  desc: Replit ID endpoint (commonly abused)
  crit: suspicious
  conf: 0.85
  attack: T1071
  if:
    type: string
    regex: '[a-f0-9-]+\.id\.repl\.co'
- id: glitch-hosted
  desc: Contacts Glitch-hosted endpoint
  crit: suspicious
  conf: 0.8
  attack: T1071
  if:
    type: string
    regex: '[a-z0-9-]+\.glitch\.me'
- id: railway-hosted
  desc: Contacts Railway-hosted endpoint
  crit: notable
  conf: 0.75
  attack: T1071
  if:
    type: string
    regex: '[a-z0-9-]+\.railway\.app'
- id: render-hosted
  desc: Contacts Render-hosted endpoint
  crit: notable
  conf: 0.75
  attack: T1071
  if:
    type: string
    regex: '[a-z0-9-]+\.onrender\.com'
- id: heroku-hosted
  desc: Contacts Heroku-hosted endpoint
  crit: notable
  conf: 0.7
  attack: T1071
  if:
    type: string
    regex: '[a-z0-9-]+\.herokuapp\.com'
- id: serveo-tunnel
  desc: Serveo SSH tunnel endpoint (reverse shell)
  crit: suspicious
  conf: 0.95
  attack: T1572
  if:
    type: string
    regex: serveo\.net
- id: localtunnel
  desc: Localtunnel endpoint (reverse shell infrastructure)
  crit: suspicious
  conf: 0.85
  attack: T1572
  if:
    type: string
    regex: '[a-z0-9-]+\.loca\.lt'
- id: localhost-run
  desc: Localhost.run tunnel endpoint
  crit: suspicious
  conf: 0.85
  attack: T1572
  if:
    type: string
    regex: '[a-z0-9-]+\.localhost\.run'
- id: cloudflare-tunnel
  desc: Cloudflare tunnel endpoint
  crit: notable
  conf: 0.7
  attack: T1572
  if:
    type: string
    regex: '[a-z0-9-]+\.trycloudflare\.com'
- id: chisel-client
  desc: Chisel client command
  crit: notable
  conf: 0.7
  attack: T1572
  if:
    type: string
    regex: chisel\s+client
- id: chisel-server
  desc: Chisel server command
  crit: notable
  conf: 0.7
  attack: T1572
  if:
    type: string
    regex: chisel\s+server
- id: hardcoded-domain-suspicious-pattern
  desc: Hardcoded suspicious TLD domain pattern
  crit: suspicious
  conf: 0.85
  unless:
  - type: raw
    regex: sina\.com\.cn|163\.com|126\.com|sohu\.com|qq\.com|yahoo\.com\.cn|mysite|rambler\.ru|yandex\.ru|mail\.ru|tbcdn\.cn|xn--hgi\.ws
  if:
    type: raw
    regex: '[''\"](?:https?://)?(?:[a-zA-Z0-9-]{1,63}\.){1,4}(?:ru|cn|xyz|top)'
- id: suspicious-php-filename
  desc: Suspicious PHP endpoint URL (gate/upload/etc)
  crit: suspicious
  conf: 0.85
  if:
    type: string
    regex: https?://[^/]{1,120}/.{0,120}(?:gate|cmd|shell|payload)\.php
- id: internal-api-probe
  desc: Probes internal network API endpoints
  crit: suspicious
  conf: 0.9
  attack: T1046
  for:
  - javascript
  - typescript
  if:
    type: string
    regex: http://(?:internal|localhost|10\.)[-a-zA-Z0-9.]*/(?:api|health|status)
- id: dynamic-dns-domain-pattern
  desc: Dynamic DNS domain pattern
  crit: suspicious
  conf: 0.9
  if:
    type: string
    regex: \b[a-zA-Z0-9][-a-zA-Z0-9]*\.(?:duckdns|no-ip|ddns|hopto)\.[a-z]{2,6}\b
composite_rules:
- id: c2-domain
  desc: Likely C2 domain (suspicious TLD)
  crit: notable
  conf: 0.85
  size_max: 5000
  any:
  - id: hardcoded-domain-suspicious-pattern
  - id: dynamic-dns-domain-pattern
- id: malware-hosting
  desc: Contacts known malware/payload hosting service
  crit: notable
  conf: 0.95
  attack: T1105
  any:
  - id: bullethost-cloud
  - id: anonfiles-com
  - id: gofile-io
  - id: transfer-sh
  - id: tmpfiles-org
  - id: catbox-moe
  - id: uguu-se
  - id: pomf-cat
  - id: 0x0-st
  - id: file-io
  - id: filedropper-com
  - id: doko-moe
- id: php-collector
  desc: Contacts PHP data collection endpoint
  crit: notable
  conf: 0.85
  attack: T1041
  any:
  - id: php-collect
  - id: php-log
  - id: php-report
  - id: php-beacon
  - id: php-gate
- id: serverless-function
  desc: Contacts serverless function endpoint (Lambda, etc)
  crit: notable
  conf: 0.7
  attack: T1071
  any:
  - id: aws-api-gateway
  - id: azure-websites
  - id: google-cloud-functions
  - id: vercel-app
  - id: netlify-app
- id: ngrok-tunnel
  desc: Contacts ngrok tunnel endpoint
  crit: suspicious
  conf: 0.9
  attack: T1071
  any:
  - id: ngrok-io
  - id: ngrok-free-app
- id: paste-service
  desc: Contacts paste/bin service (common payload hosting)
  crit: suspicious
  conf: 0.85
  attack: T1102
  any:
  - id: pastebin-com
  - id: hastebin-com
  - id: ghostbin-com
  - id: paste-ee
  - id: dpaste-com
  - id: privatebin-net
  - id: rentry-co
- id: replit-hosted
  desc: Contacts Replit-hosted endpoint (commonly abused)
  crit: suspicious
  conf: 0.85
  attack: T1071
  any:
  - id: replit-dev
  - id: repl-co
  - id: replit-id-domain
- id: chisel-tunnel
  desc: Chisel reverse tunnel infrastructure
  crit: suspicious
  conf: 0.95
  attack: T1572
  any:
  - id: chisel-client
  - id: chisel-server
  - id: well-known/tools/offensive::chisel-ref
