# Default Credential Detection
# Common default passwords used in brute-force attacks
# ATT&CK: T1110.001 (Brute Force: Password Guessing)

traits:
  - id: numeric-123456
    desc: "Default credential: 123456"
    crit: suspicious
    conf: 0.8
    attack: "T1110.001"
    for: [elf]
    if:
      type: string
      # Avoid matching ASCII character tables (0123456789...)
      # Require 123456 not preceded by 0-5 and not followed by 7-9
      regex: "(?<![0-5])123456(?![7-9])"

  # NOTE: "password" alone is too common (system utilities, config, etc.)
  # Real credential brute-force detection requires multiple indicators
  # Match "password" only with control char delimiters suggesting credential list
  - id: literal-password
    desc: "Default credential: password"
    crit: notable
    conf: 0.4
    attack: "T1110.001"
    for: [elf]
    if:
      type: string
      # Require credential list context: control chars as delimiters or user:password format
      regex: "(?:[\\x00-\\x1f]password[\\x00-\\x1f]?|\\b\\w+:password\\b)"

  - id: admin123
    desc: "Default credential: admin123"
    crit: suspicious
    conf: 0.85
    attack: "T1110.001"
    for: [elf]
    if:
      type: string
      substr: "admin123"

  - id: literal-default
    desc: "Default credential: default"
    crit: notable
    conf: 0.5
    attack: "T1110.001"
    for: [elf]
    if:
      type: string
      # Word "default" alone is common - require it with control char prefix
      # which suggests credential list with delimiters
      regex: "[\\x00-\\x1f]default[\\x00-\\x1f]?"

  # NOTE: "support" alone is extremely common in system utilities and config
  # Removed as standalone trait - only relevant in composite credential dictionary
  # - id: credential/brute-force/password/support

  - id: guest
    desc: "Default credential: guest"
    crit: notable
    conf: 0.7
    attack: "T1110.001"
    for: [elf]
    if:
      type: string
      # Match guest in credential context (user:pass combo or with control chars)
      regex: "(?:[\\x00-\\x1f]guest[\\x00-\\x1f]?|\\bguest:)"

  # === IoT ZTE credential atomic indicators ===
  - id: iot-pte521
    desc: "Default IoT credential: Pte521"
    crit: suspicious
    conf: 0.9
    attack: "T1110.001"
    for: [elf]
    if:
      type: string
      substr: "Pte521"

  - id: iot-pon521
    desc: "Default IoT credential: Pon521"
    crit: suspicious
    conf: 0.9
    attack: "T1110.001"
    for: [elf]
    if:
      type: string
      substr: "Pon521"

  - id: iot-zxic521
    desc: "Default IoT credential: Zxic521"
    crit: suspicious
    conf: 0.9
    attack: "T1110.001"
    for: [elf]
    if:
      type: string
      substr: "Zxic521"

  - id: telnet-combo
    desc: "Telnet username:password combo format"
    crit: suspicious
    conf: 0.8
    attack: "T1110.001"
    for: [elf]
    # Size constraint: Credential dictionaries are typically in small malware droppers
    # Large legitimate binaries may have user:X patterns in help text, config, etc.
    size_max: 100000
    if:
      type: string
      # Match credential combos but exclude common programming patterns like
      # user:group, user:groupFilter, root:path, etc.
      regex: "\\b(root|admin|user|guest|support):(root|admin|1234|pass|default|qwerty|letmein|[a-zA-Z0-9]{4,8})\\b"
    not:
      - "user:group"
      - "user:uid"
      - "user:request"
      - "root:path"
      - "root:/"
      # Exclude help text patterns from CLI tools
      - "<user:password>"
      - "user:password>"
      - "--user <"
      - "-u, --user"
    unless:
      # Exclude curl/libcurl which has credential help text
      - id: cap/comm/download/curl::curl-easy-init

  # Real brute-force dictionaries have many credential entries packed densely.
  # A few scattered credential-like strings are common in help text; 10+ entries
  # in a small file is a true embedded dictionary.
  - id: credential-wordlist
    desc: "Dense credential wordlist (brute-force dictionary)"
    crit: suspicious
    conf: 0.92
    attack: "T1110.001"
    for: [elf]
    size_max: 200000
    if:
      type: string
      # Match common credential patterns with delimiters
      regex: "(?:[\\x00-\\x1f](?:admin|root|password|default|guest|user|1234|qwerty)[\\x00-\\x1f]?)"
      count_min: 15
      per_kb_min: 0.5
    unless:
      - id: cap/interface/usage/usage-help

composite_rules:
  # IoT ZTE credential composite
  - id: iot-zte
    desc: "Default IoT credential: ZTE router"
    crit: suspicious
    conf: 0.95
    attack: "T1110.001"
    for: [elf]
    needs: 1
    any:
      - id: obj/lateral/brute-force/iot-creds::router-cred-zte
      - id: iot-pte521
      - id: iot-pon521
      - id: iot-zxic521

  - id: dictionary
    desc: "Embedded credential brute-force dictionary"
    crit: suspicious
    conf: 0.9
    mbc: "E1040"
    attack: "T1110.001"
    for: [elf]
    needs: 4
    any:
      - id: obj/creds/username/admin::detected
      - id: obj/creds/username/root::detected
      - id: guest
      - id: numeric-123456
      - id: literal-password
      - id: admin123
      - id: literal-default
