composite_rules:
  - id: obfuscated-jscript-c2-ip
    desc: Hardcoded IP in JScript file
    crit: suspicious
    conf: 0.9
    all:
      - id: cap/host/interpreter/jscript::is-jscript
      - id: obj/c2/infrastructure/ip::hardcoded-ipv4-script
