# C2 Infrastructure Detection - IP Addresses
# Detects hardcoded IP addresses, ports, and obfuscated C2 patterns
# ATT&CK: T1071.001

defaults:
  # IP address strings can appear in any file type
  for: ["*"]
  mbc: "C0002"
  attack: "T1071.001"
  crit: suspicious

traits:
  - id: hardcoded-ipv4
    desc: Hardcoded external IPv4 address
    crit: notable
    conf: 0.85
    mbc: "C0002"
    attack: "T1071.001"
    # Exclude PE/bootloader files where string extraction is unreliable
    # (instruction bytes get parsed as IPs). More reliable in ELF/scripts/macho.
    for: [elf, macho, shell, python, ruby, javascript, php]
    if:
      type: string
      # Match IP-like patterns; external_ip validates they're routable external addresses
      regex: '\b[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\b'
      external_ip: true

  - id: http-raw-ip-url-content
    desc: HTTP direct IP in binary content
    crit: suspicious
    conf: 0.90
    mbc: "B0030"
    attack: "T1071.001"
    if:
      type: content
      # Match HTTP URLs with IP addresses; external_ip validates they're routable
      regex: 'https?://[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}[/:]'
      external_ip: true

  - id: http-raw-ip-url-string
    desc: HTTP direct IP in extracted strings
    crit: suspicious
    conf: 0.95
    mbc: "B0030"
    attack: "T1071.001"
    if:
      type: string
      # Match HTTP URLs with IP addresses; external_ip validates they're routable
      regex: 'https?://[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
      external_ip: true

  # === Port number atomic indicators ===
  - id: port-23
    desc: "Port 23 (telnet)"
    crit: inert
    conf: 0.5
    if:
      type: string
      regex: ":23\\b"

  - id: port-80
    desc: "Port 80 (HTTP)"
    crit: inert
    conf: 0.4
    if:
      type: string
      regex: ":80\\b"

  - id: port-443
    desc: "Port 443 (HTTPS)"
    crit: inert
    conf: 0.4
    if:
      type: string
      regex: ":443\\b"

  - id: port-8080
    desc: "Port 8080 (HTTP alt)"
    crit: inert
    conf: 0.5
    if:
      type: string
      regex: ":8080\\b"

  - id: port-4444
    desc: "Port 4444 (Metasploit default)"
    crit: inert
    conf: 0.6
    if:
      type: string
      regex: ":4444\\b"

  - id: port-1337
    desc: "Port 1337 (leet)"
    crit: inert
    conf: 0.5
    if:
      type: string
      regex: ":1337\\b"

  - id: port-31337
    desc: "Port 31337 (eleet)"
    crit: inert
    conf: 0.6
    if:
      type: string
      regex: ":31337\\b"

composite_rules:
  - id: port-number-constant
    desc: "Common C2 port number (23,"
    crit: inert
    conf: 0.6
    mbc: none
    attack: none
    needs: 1
    any:
      - id: port-23
      - id: port-80
      - id: port-443
      - id: port-8080
      - id: port-4444
      - id: port-1337
      - id: port-31337

  - id: private-ip-reference
    desc: "Private/internal IP address reference"
    crit: notable
    conf: 0.75
    mbc: none
    attack: none
    needs: 1
    any:
      - id: private-ip-10
      - id: private-ip-172
      - id: private-ip-192

  - id: obfuscated-address
    desc: "C2 address obfuscation (HTTP client"
    conf: 0.85
    mbc: "B0032"
    attack: "T1027"
    for: [elf]
    all:
      - id: truncated-http-url
    none:
      - id: hardcoded-ipv4

  - id: dynamic-ip
    desc: "Dynamic IP address construction"
    conf: 0.8
    mbc: "B0032"
    attack: "T1027"
    all:
      - id: ip-format-string
    none:
      - id: hardcoded-ipv4
