# C2 Infrastructure Detection - IP Addresses
# Detects hardcoded IP addresses, ports, and obfuscated C2 patterns
# ATT&CK: T1071.001

defaults:
  # IP address strings can appear in any file type
  for: ["*"]
  mbc: "C0002"
  attack: "T1071.001"
  crit: suspicious

traits:
  # For binaries: use extracted strings which are more reliable
  - id: hardcoded-ipv4-binary
    desc: Hardcoded external IPv4 address
    crit: notable
    conf: 0.85
    mbc: "C0002"
    attack: "T1071.001"
    # Size constraint: Large binaries (Rust/Go with regex, Unicode tables, SQLite) often have
    # byte patterns that look like IPs. C2 implants are typically compact (<1.5MB).
    size_max: 1500000
    for: [elf, macho, pe]
    if:
      type: string
      # Match standalone IPv4 literals; avoid opcode/data artifacts like "A.B.C.D:port"
      regex: '^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$'
      external_ip: true

  # For scripts: use extracted strings to skip comments and non-code content
  - id: hardcoded-ipv4-script
    desc: Hardcoded external IPv4 address
    crit: notable
    conf: 0.85
    mbc: "C0002"
    attack: "T1071.001"
    for: [scripts]
    # Small binaries with hardcoded IPs are more suspicious
    size_max: 5000
    if:
      type: string
      # Require a standalone literal to avoid matching prose/docstrings that only
      # contain an IPv4-like substring.
      regex: '^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$'
      external_ip: true
      exclude_patterns:
        - "^8\\.8\\.[84]\\.[84]$"
        - "^1\\.1\\.1\\.1$"
        - "^9\\.9\\.9\\.9$"
        - "^208\\.67\\.22[20]\\.22[20]$"
    unless:
      - type: raw
        regex: "pytest|def test_"

  - id: http-raw-ip-url
    desc: HTTP direct IP in extracted strings
    crit: suspicious
    conf: 0.95
    mbc: "B0030"
    attack: "T1071.001"
    for: [elf, macho, pe, scripts]
    if:
      type: string
      # Match HTTP URLs with IP addresses; external_ip validates they're routable
      regex: 'https?://[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
      external_ip: true

  # === Port number atomic indicators ===
  - id: port-23
    desc: "Port 23 (telnet)"
    crit: inert
    conf: 0.5
    if:
      type: string
      regex: ":23\\b"

  - id: port-80
    desc: "Port 80 (HTTP)"
    crit: inert
    conf: 0.4
    if:
      type: string
      regex: ":80\\b"

  - id: port-443
    desc: "Port 443 (HTTPS)"
    crit: inert
    conf: 0.4
    if:
      type: string
      regex: ":443\\b"

  - id: port-8080
    desc: "Port 8080 (HTTP alt)"
    crit: inert
    conf: 0.5
    if:
      type: string
      regex: ":8080\\b"

  - id: port-4444
    desc: "Port 4444 (Metasploit default)"
    crit: inert
    conf: 0.6
    if:
      type: string
      regex: ":4444\\b"

  - id: port-1337
    desc: "Port 1337 (leet)"
    crit: inert
    conf: 0.5
    if:
      type: string
      regex: ":1337\\b"

  - id: port-31337
    desc: "Port 31337 (eleet)"
    crit: inert
    conf: 0.6
    if:
      type: string
      regex: ":31337\\b"

composite_rules:
  - id: port-number-constant
    desc: "Common C2 port number (23,"
    crit: inert
    conf: 0.6
    mbc: none
    attack: none
    any:
      - id: port-23
      - id: port-80
      - id: port-443
      - id: port-8080
      - id: port-4444
      - id: port-1337
      - id: port-31337

