//! Syscall name mapping for various architectures
//! Maps syscall numbers to human-readable names and descriptions

#![allow(dead_code)]

/// Get syscall name for the given architecture and number
pub fn syscall_name(arch: &str, number: u32) -> String {
    match arch {
        "mips" => mips_syscall_name(number),
        "x86" => x86_syscall_name(number),
        "x86_64" => x86_64_syscall_name(number),
        "arm" => arm_syscall_name(number),
        "aarch64" => aarch64_syscall_name(number),
        "ppc" => ppc_syscall_name(number),
        _ => format!("syscall_{}", number),
    }
}

/// Get a brief description of what the syscall does (architecture-independent)
pub fn syscall_description(name: &str) -> String {
    match name {
        // Process lifecycle
        "exit" | "_exit" | "exit_group" => "terminates process",
        "fork" => "creates child process",
        "vfork" => "creates child process sharing memory",
        "clone" | "clone3" => "creates process or thread",
        "execve" | "execveat" => "executes program",
        "wait4" | "waitpid" | "waitid" => "waits for child process",
        "kill" | "tkill" | "tgkill" => "sends signal to process",

        // Process identity
        "getpid" => "gets process ID",
        "getppid" => "gets parent process ID",
        "getuid" | "getuid32" => "gets user ID",
        "geteuid" | "geteuid32" => "gets effective user ID",
        "getgid" | "getgid32" => "gets group ID",
        "getegid" | "getegid32" => "gets effective group ID",
        "setuid" | "setuid32" => "sets user ID",
        "seteuid" => "sets effective user ID",
        "setgid" | "setgid32" => "sets group ID",
        "setreuid" | "setreuid32" => "sets real and effective user ID",
        "setregid" | "setregid32" => "sets real and effective group ID",
        "setresuid" | "setresuid32" => "sets real, effective, saved user ID",
        "setresgid" | "setresgid32" => "sets real, effective, saved group ID",
        "setsid" => "creates new session (daemon)",
        "setpgid" => "sets process group ID",
        "getpgrp" | "getpgid" => "gets process group ID",
        "getsid" => "gets session ID",

        // File operations
        "open" | "openat" | "openat2" => "opens file",
        "close" => "closes file descriptor",
        "read" | "pread64" | "readv" | "preadv" | "preadv2" => "reads from file",
        "write" | "pwrite64" | "writev" | "pwritev" | "pwritev2" => "writes to file",
        "lseek" | "_llseek" => "repositions file offset",
        "creat" => "creates file",
        "unlink" | "unlinkat" => "deletes file",
        "rename" | "renameat" | "renameat2" => "renames file",
        "link" | "linkat" => "creates hard link",
        "symlink" | "symlinkat" => "creates symbolic link",
        "readlink" | "readlinkat" => "reads symbolic link",
        "mkdir" | "mkdirat" => "creates directory",
        "rmdir" => "removes directory",
        "chdir" => "changes working directory",
        "fchdir" => "changes working directory via fd",
        "getcwd" => "gets current working directory",
        "chmod" | "fchmod" | "fchmodat" => "changes file permissions",
        "chown" | "fchown" | "lchown" | "fchownat" => "changes file ownership",
        "stat" | "fstat" | "lstat" | "newfstatat" | "statx" => "gets file status",
        "access" | "faccessat" | "faccessat2" => "checks file permissions",
        "truncate" | "ftruncate" => "truncates file",
        "dup" | "dup2" | "dup3" => "duplicates file descriptor",
        "fcntl" | "fcntl64" => "file descriptor control",
        "ioctl" => "device control",
        "flock" => "applies file lock",
        "fsync" | "fdatasync" => "synchronizes file to disk",
        "utimes" | "futimesat" | "utimensat" => "changes file timestamps",

        // Memory
        "mmap" | "mmap2" => "maps memory",
        "munmap" => "unmaps memory",
        "mprotect" => "sets memory protection",
        "mremap" => "remaps memory",
        "brk" => "changes data segment size",
        "mlock" | "mlock2" | "mlockall" => "locks memory",
        "munlock" | "munlockall" => "unlocks memory",
        "msync" => "synchronizes memory with file",
        "madvise" => "advises kernel about memory usage",
        "memfd_create" => "creates anonymous file in memory",

        // Network - sockets
        "socket" => "creates network socket",
        "socketpair" => "creates pair of connected sockets",
        "bind" => "binds socket to address",
        "listen" => "listens for connections",
        "accept" | "accept4" => "accepts connection",
        "connect" => "connects to remote host",
        "send" | "sendto" | "sendmsg" | "sendmmsg" => "sends data over network",
        "recv" | "recvfrom" | "recvmsg" | "recvmmsg" => "receives data from network",
        "shutdown" => "shuts down socket",
        "getsockopt" => "gets socket options",
        "setsockopt" => "sets socket options",
        "getsockname" => "gets socket address",
        "getpeername" => "gets peer address",
        "socketcall" => "socket system call multiplexer",

        // IPC
        "pipe" | "pipe2" => "creates pipe",
        "msgget" => "gets message queue",
        "msgsnd" => "sends message to queue",
        "msgrcv" => "receives message from queue",
        "msgctl" => "message queue control",
        "semget" => "gets semaphore set",
        "semop" | "semtimedop" => "semaphore operations",
        "semctl" => "semaphore control",
        "shmget" => "gets shared memory segment",
        "shmat" => "attaches shared memory",
        "shmdt" => "detaches shared memory",
        "shmctl" => "shared memory control",

        // Time
        "time" => "gets current time",
        "gettimeofday" => "gets time of day",
        "settimeofday" => "sets time of day",
        "clock_gettime" | "clock_gettime64" => "gets clock time",
        "clock_settime" | "clock_settime64" => "sets clock time",
        "nanosleep" | "clock_nanosleep" => "sleeps for specified time",
        "alarm" => "sets alarm clock",
        "setitimer" => "sets interval timer",
        "getitimer" => "gets interval timer",

        // Signals
        "sigaction" | "rt_sigaction" => "sets signal handler",
        "sigprocmask" | "rt_sigprocmask" => "changes signal mask",
        "sigreturn" | "rt_sigreturn" => "returns from signal handler",
        "sigsuspend" | "rt_sigsuspend" => "waits for signal",
        "sigpending" | "rt_sigpending" => "gets pending signals",
        "signalfd" | "signalfd4" => "creates signal file descriptor",

        // System info
        "uname" => "gets system information",
        "sysinfo" => "gets system statistics",
        "getrlimit" | "prlimit64" => "gets resource limits",
        "setrlimit" => "sets resource limits",
        "getrusage" => "gets resource usage",
        "syslog" => "reads/controls kernel log",
        "prctl" => "process control operations",
        "arch_prctl" => "architecture-specific process control",
        "seccomp" => "operates on seccomp filters",

        // Mount/filesystem
        "mount" => "mounts filesystem",
        "umount" | "umount2" => "unmounts filesystem",
        "pivot_root" => "changes root filesystem",
        "chroot" => "changes root directory",
        "statfs" | "fstatfs" => "gets filesystem statistics",
        "sync" | "syncfs" => "synchronizes filesystem",

        // Debugging/tracing
        "ptrace" => "traces/controls process (debugger)",
        "process_vm_readv" => "reads from another process memory",
        "process_vm_writev" => "writes to another process memory",

        // Misc
        "poll" | "ppoll" => "waits for events on file descriptors",
        "select" | "pselect6" => "synchronous I/O multiplexing",
        "epoll_create" | "epoll_create1" => "creates epoll instance",
        "epoll_ctl" => "controls epoll instance",
        "epoll_wait" | "epoll_pwait" | "epoll_pwait2" => "waits for epoll events",
        "eventfd" | "eventfd2" => "creates event file descriptor",
        "timerfd_create" => "creates timer file descriptor",
        "inotify_init" | "inotify_init1" => "creates inotify instance",
        "inotify_add_watch" => "adds inotify watch",
        "getrandom" => "gets random bytes",
        "mknod" | "mknodat" => "creates special file",
        "getdents" | "getdents64" => "reads directory entries",
        "reboot" => "reboots system",
        "sethostname" => "sets hostname",
        "setdomainname" => "sets domain name",
        "init_module" | "finit_module" => "loads kernel module",
        "delete_module" => "unloads kernel module",
        "kexec_load" | "kexec_file_load" => "loads new kernel for kexec",
        "setns" => "reassociates thread with namespace",
        "unshare" => "disassociates parts of execution context",
        "personality" => "sets process execution domain",
        "capget" => "gets process capabilities",
        "capset" => "sets process capabilities",

        _ => "system call",
    }
    .to_string()
}

/// MIPS o32 syscalls (base 4000)
fn mips_syscall_name(number: u32) -> String {
    match number {
        4001 => "exit",
        4002 => "fork",
        4003 => "read",
        4004 => "write",
        4005 => "open",
        4006 => "close",
        4007 => "waitpid",
        4008 => "creat",
        4009 => "link",
        4010 => "unlink",
        4011 => "execve",
        4012 => "chdir",
        4013 => "time",
        4014 => "mknod",
        4015 => "chmod",
        4016 => "lchown",
        4019 => "lseek",
        4020 => "getpid",
        4021 => "mount",
        4022 => "umount",
        4023 => "setuid",
        4024 => "getuid",
        4026 => "ptrace",
        4033 => "access",
        4037 => "kill",
        4038 => "rename",
        4039 => "mkdir",
        4040 => "rmdir",
        4041 => "dup",
        4042 => "pipe",
        4045 => "brk",
        4054 => "ioctl",
        4055 => "fcntl",
        4057 => "setpgid",
        4063 => "dup2",
        4064 => "getppid",
        4065 => "getpgrp",
        4066 => "setsid",
        4072 => "sigsuspend",
        4076 => "getrlimit",
        4077 => "getrusage",
        4078 => "gettimeofday",
        4079 => "settimeofday",
        4083 => "symlink",
        4085 => "readlink",
        4090 => "mmap",
        4091 => "munmap",
        4093 => "ftruncate",
        4094 => "fchmod",
        4095 => "fchown",
        4096 => "getpriority",
        4097 => "setpriority",
        4102 => "socketcall",
        4103 => "syslog",
        4104 => "setitimer",
        4105 => "getitimer",
        4106 => "stat",
        4107 => "lstat",
        4108 => "fstat",
        4114 => "wait4",
        4116 => "sysinfo",
        4120 => "clone",
        4122 => "uname",
        4125 => "mprotect",
        4133 => "fchdir",
        4140 => "_llseek",
        4141 => "getdents",
        4142 => "_newselect",
        4143 => "flock",
        4144 => "msync",
        4145 => "readv",
        4146 => "writev",
        4147 => "cacheflush",
        4153 => "sched_setparam",
        4154 => "sched_getparam",
        4155 => "sched_setscheduler",
        4167 => "mremap",
        4168 => "accept",
        4169 => "bind",
        4170 => "connect",
        4171 => "getpeername",
        4172 => "getsockname",
        4173 => "getsockopt",
        4174 => "listen",
        4175 => "recv",
        4176 => "recvfrom",
        4177 => "recvmsg",
        4178 => "send",
        4179 => "sendmsg",
        4180 => "sendto",
        4181 => "setsockopt",
        4182 => "shutdown",
        4183 => "socket",
        4184 => "socketpair",
        4185 => "setresuid",
        4186 => "getresuid",
        4188 => "poll",
        4194 => "rt_sigaction",
        4195 => "rt_sigprocmask",
        4198 => "rt_sigsuspend",
        4199 => "pread64",
        4200 => "pwrite64",
        4203 => "setreuid",
        4204 => "setregid",
        4206 => "ftruncate64",
        4207 => "stat64",
        4208 => "lstat64",
        4209 => "fstat64",
        4210 => "pivot_root",
        4213 => "setuid",
        4214 => "setgid",
        4216 => "getdents64",
        4217 => "fcntl64",
        4220 => "gettid",
        4221 => "readahead",
        4222 => "setxattr",
        4230 => "removexattr",
        4238 => "tkill",
        4240 => "futex",
        4241 => "sched_setaffinity",
        4242 => "sched_getaffinity",
        4245 => "io_setup",
        4249 => "io_getevents",
        4250 => "io_submit",
        4251 => "io_cancel",
        4252 => "exit_group",
        4263 => "clock_gettime",
        4264 => "clock_getres",
        4265 => "clock_nanosleep",
        4266 => "statfs64",
        4267 => "fstatfs64",
        4268 => "tgkill",
        4269 => "utimes",
        4283 => "openat",
        4284 => "mkdirat",
        4285 => "mknodat",
        4286 => "fchownat",
        4288 => "fstatat64",
        4289 => "unlinkat",
        4290 => "renameat",
        4291 => "linkat",
        4292 => "symlinkat",
        4293 => "readlinkat",
        4294 => "fchmodat",
        4295 => "faccessat",
        4296 => "pselect6",
        4297 => "ppoll",
        4298 => "unshare",
        4302 => "splice",
        4305 => "tee",
        4306 => "vmsplice",
        4309 => "set_robust_list",
        4310 => "get_robust_list",
        4311 => "getcpu",
        4312 => "epoll_pwait",
        4316 => "utimensat",
        4317 => "signalfd",
        4318 => "timerfd_create",
        4319 => "eventfd",
        4320 => "fallocate",
        4321 => "timerfd_gettime",
        4322 => "timerfd_settime",
        4323 => "signalfd4",
        4324 => "eventfd2",
        4325 => "epoll_create1",
        4326 => "dup3",
        4327 => "pipe2",
        4328 => "inotify_init1",
        4329 => "preadv",
        4330 => "pwritev",
        4334 => "fanotify_init",
        4335 => "fanotify_mark",
        4336 => "prlimit64",
        4337 => "name_to_handle_at",
        4338 => "open_by_handle_at",
        4339 => "clock_adjtime",
        4340 => "syncfs",
        4341 => "sendmmsg",
        4342 => "setns",
        4343 => "process_vm_readv",
        4344 => "process_vm_writev",
        4345 => "kcmp",
        4346 => "finit_module",
        4349 => "sched_setattr",
        4350 => "sched_getattr",
        4351 => "renameat2",
        4352 => "seccomp",
        4353 => "getrandom",
        4354 => "memfd_create",
        4355 => "bpf",
        4356 => "execveat",
        4359 => "socket",
        4360 => "socketpair",
        4361 => "bind",
        4362 => "connect",
        4363 => "listen",
        4365 => "accept4",
        4366 => "getsockopt",
        4367 => "setsockopt",
        4368 => "getsockname",
        4369 => "getpeername",
        4370 => "sendto",
        4371 => "sendmsg",
        4372 => "recvfrom",
        4373 => "recvmsg",
        4374 => "shutdown",
        4393 => "membarrier",
        4394 => "mlock2",
        4396 => "preadv2",
        4397 => "pwritev2",
        4398 => "pkey_mprotect",
        4399 => "pkey_alloc",
        4400 => "pkey_free",
        4401 => "statx",
        _ => return format!("syscall_{}", number),
    }
    .to_string()
}

/// x86 (32-bit) syscalls
fn x86_syscall_name(number: u32) -> String {
    match number {
        1 => "exit",
        2 => "fork",
        3 => "read",
        4 => "write",
        5 => "open",
        6 => "close",
        7 => "waitpid",
        8 => "creat",
        9 => "link",
        10 => "unlink",
        11 => "execve",
        12 => "chdir",
        13 => "time",
        14 => "mknod",
        15 => "chmod",
        19 => "lseek",
        20 => "getpid",
        21 => "mount",
        23 => "setuid",
        24 => "getuid",
        26 => "ptrace",
        29 => "pause",
        33 => "access",
        36 => "sync",
        37 => "kill",
        38 => "rename",
        39 => "mkdir",
        40 => "rmdir",
        41 => "dup",
        42 => "pipe",
        45 => "brk",
        47 => "getgid",
        49 => "geteuid",
        50 => "getegid",
        52 => "umount2",
        54 => "ioctl",
        55 => "fcntl",
        57 => "setpgid",
        60 => "umask",
        61 => "chroot",
        63 => "dup2",
        64 => "getppid",
        65 => "getpgrp",
        66 => "setsid",
        70 => "setreuid",
        71 => "setregid",
        72 => "sigsuspend",
        74 => "sethostname",
        75 => "setrlimit",
        76 => "getrlimit",
        77 => "getrusage",
        78 => "gettimeofday",
        79 => "settimeofday",
        83 => "symlink",
        85 => "readlink",
        90 => "mmap",
        91 => "munmap",
        93 => "ftruncate",
        94 => "fchmod",
        95 => "fchown",
        96 => "getpriority",
        97 => "setpriority",
        99 => "statfs",
        102 => "socketcall",
        103 => "syslog",
        104 => "setitimer",
        105 => "getitimer",
        106 => "stat",
        107 => "lstat",
        108 => "fstat",
        114 => "wait4",
        116 => "sysinfo",
        120 => "clone",
        122 => "uname",
        125 => "mprotect",
        133 => "fchdir",
        140 => "_llseek",
        141 => "getdents",
        142 => "_newselect",
        143 => "flock",
        144 => "msync",
        145 => "readv",
        146 => "writev",
        158 => "sched_yield",
        162 => "nanosleep",
        163 => "mremap",
        168 => "poll",
        174 => "rt_sigaction",
        175 => "rt_sigprocmask",
        179 => "rt_sigsuspend",
        180 => "pread64",
        181 => "pwrite64",
        183 => "getcwd",
        186 => "sigaltstack",
        190 => "vfork",
        192 => "mmap2",
        195 => "stat64",
        196 => "lstat64",
        197 => "fstat64",
        199 => "getuid32",
        200 => "getgid32",
        201 => "geteuid32",
        202 => "getegid32",
        203 => "setreuid32",
        204 => "setregid32",
        213 => "setuid32",
        214 => "setgid32",
        219 => "madvise",
        220 => "getdents64",
        221 => "fcntl64",
        224 => "gettid",
        225 => "readahead",
        226 => "setxattr",
        240 => "futex",
        241 => "sched_setaffinity",
        242 => "sched_getaffinity",
        243 => "set_thread_area",
        244 => "get_thread_area",
        252 => "exit_group",
        254 => "epoll_create",
        255 => "epoll_ctl",
        256 => "epoll_wait",
        263 => "clock_gettime",
        264 => "clock_getres",
        265 => "clock_nanosleep",
        266 => "statfs64",
        267 => "fstatfs64",
        268 => "tgkill",
        269 => "utimes",
        270 => "fadvise64_64",
        281 => "set_tid_address",
        284 => "timer_create",
        285 => "timer_settime",
        286 => "timer_gettime",
        287 => "timer_getoverrun",
        288 => "timer_delete",
        289 => "clock_settime",
        290 => "clock_gettime",
        295 => "openat",
        296 => "mkdirat",
        297 => "mknodat",
        298 => "fchownat",
        300 => "fstatat64",
        301 => "unlinkat",
        302 => "renameat",
        303 => "linkat",
        304 => "symlinkat",
        305 => "readlinkat",
        306 => "fchmodat",
        307 => "faccessat",
        308 => "pselect6",
        309 => "ppoll",
        310 => "unshare",
        311 => "set_robust_list",
        312 => "get_robust_list",
        313 => "splice",
        314 => "sync_file_range",
        315 => "tee",
        316 => "vmsplice",
        318 => "getcpu",
        319 => "epoll_pwait",
        320 => "utimensat",
        321 => "signalfd",
        322 => "timerfd_create",
        323 => "eventfd",
        324 => "fallocate",
        325 => "timerfd_settime",
        326 => "timerfd_gettime",
        327 => "signalfd4",
        328 => "eventfd2",
        329 => "epoll_create1",
        330 => "dup3",
        331 => "pipe2",
        332 => "inotify_init1",
        333 => "preadv",
        334 => "pwritev",
        336 => "recvmmsg",
        339 => "prlimit64",
        340 => "name_to_handle_at",
        341 => "open_by_handle_at",
        342 => "clock_adjtime",
        343 => "syncfs",
        344 => "sendmmsg",
        345 => "setns",
        346 => "process_vm_readv",
        347 => "process_vm_writev",
        348 => "kcmp",
        349 => "finit_module",
        352 => "sched_setattr",
        353 => "sched_getattr",
        354 => "renameat2",
        355 => "seccomp",
        356 => "getrandom",
        357 => "memfd_create",
        358 => "bpf",
        359 => "execveat",
        364 => "socket",
        365 => "socketpair",
        366 => "bind",
        367 => "connect",
        368 => "listen",
        369 => "accept4",
        370 => "getsockopt",
        371 => "setsockopt",
        372 => "getsockname",
        373 => "getpeername",
        374 => "sendto",
        375 => "sendmsg",
        376 => "recvfrom",
        377 => "recvmsg",
        378 => "shutdown",
        _ => return format!("syscall_{}", number),
    }
    .to_string()
}

/// x86_64 syscalls
fn x86_64_syscall_name(number: u32) -> String {
    match number {
        0 => "read",
        1 => "write",
        2 => "open",
        3 => "close",
        4 => "stat",
        5 => "fstat",
        6 => "lstat",
        7 => "poll",
        8 => "lseek",
        9 => "mmap",
        10 => "mprotect",
        11 => "munmap",
        12 => "brk",
        13 => "rt_sigaction",
        14 => "rt_sigprocmask",
        15 => "rt_sigreturn",
        16 => "ioctl",
        17 => "pread64",
        18 => "pwrite64",
        19 => "readv",
        20 => "writev",
        21 => "access",
        22 => "pipe",
        23 => "select",
        24 => "sched_yield",
        25 => "mremap",
        26 => "msync",
        27 => "mincore",
        28 => "madvise",
        29 => "shmget",
        30 => "shmat",
        31 => "shmctl",
        32 => "dup",
        33 => "dup2",
        34 => "pause",
        35 => "nanosleep",
        36 => "getitimer",
        37 => "alarm",
        38 => "setitimer",
        39 => "getpid",
        40 => "sendfile",
        41 => "socket",
        42 => "connect",
        43 => "accept",
        44 => "sendto",
        45 => "recvfrom",
        46 => "sendmsg",
        47 => "recvmsg",
        48 => "shutdown",
        49 => "bind",
        50 => "listen",
        51 => "getsockname",
        52 => "getpeername",
        53 => "socketpair",
        54 => "setsockopt",
        55 => "getsockopt",
        56 => "clone",
        57 => "fork",
        58 => "vfork",
        59 => "execve",
        60 => "exit",
        61 => "wait4",
        62 => "kill",
        63 => "uname",
        64 => "semget",
        65 => "semop",
        66 => "semctl",
        67 => "shmdt",
        68 => "msgget",
        69 => "msgsnd",
        70 => "msgrcv",
        71 => "msgctl",
        72 => "fcntl",
        73 => "flock",
        74 => "fsync",
        75 => "fdatasync",
        76 => "truncate",
        77 => "ftruncate",
        78 => "getdents",
        79 => "getcwd",
        80 => "chdir",
        81 => "fchdir",
        82 => "rename",
        83 => "mkdir",
        84 => "rmdir",
        85 => "creat",
        86 => "link",
        87 => "unlink",
        88 => "symlink",
        89 => "readlink",
        90 => "chmod",
        91 => "fchmod",
        92 => "chown",
        93 => "fchown",
        94 => "lchown",
        95 => "umask",
        96 => "gettimeofday",
        97 => "getrlimit",
        98 => "getrusage",
        99 => "sysinfo",
        100 => "times",
        101 => "ptrace",
        102 => "getuid",
        103 => "syslog",
        104 => "getgid",
        105 => "setuid",
        106 => "setgid",
        107 => "geteuid",
        108 => "getegid",
        109 => "setpgid",
        110 => "getppid",
        111 => "getpgrp",
        112 => "setsid",
        113 => "setreuid",
        114 => "setregid",
        115 => "getgroups",
        116 => "setgroups",
        117 => "setresuid",
        118 => "getresuid",
        119 => "setresgid",
        120 => "getresgid",
        121 => "getpgid",
        122 => "setfsuid",
        123 => "setfsgid",
        124 => "getsid",
        125 => "capget",
        126 => "capset",
        127 => "rt_sigpending",
        128 => "rt_sigtimedwait",
        129 => "rt_sigqueueinfo",
        130 => "rt_sigsuspend",
        131 => "sigaltstack",
        132 => "utime",
        133 => "mknod",
        135 => "personality",
        136 => "ustat",
        137 => "statfs",
        138 => "fstatfs",
        139 => "sysfs",
        140 => "getpriority",
        141 => "setpriority",
        142 => "sched_setparam",
        143 => "sched_getparam",
        144 => "sched_setscheduler",
        145 => "sched_getscheduler",
        146 => "sched_get_priority_max",
        147 => "sched_get_priority_min",
        148 => "sched_rr_get_interval",
        149 => "mlock",
        150 => "munlock",
        151 => "mlockall",
        152 => "munlockall",
        153 => "vhangup",
        154 => "modify_ldt",
        155 => "pivot_root",
        156 => "_sysctl",
        157 => "prctl",
        158 => "arch_prctl",
        159 => "adjtimex",
        160 => "setrlimit",
        161 => "chroot",
        162 => "sync",
        163 => "acct",
        164 => "settimeofday",
        165 => "mount",
        166 => "umount2",
        167 => "swapon",
        168 => "swapoff",
        169 => "reboot",
        170 => "sethostname",
        171 => "setdomainname",
        172 => "iopl",
        173 => "ioperm",
        175 => "init_module",
        176 => "delete_module",
        179 => "quotactl",
        186 => "gettid",
        187 => "readahead",
        188 => "setxattr",
        189 => "lsetxattr",
        190 => "fsetxattr",
        191 => "getxattr",
        192 => "lgetxattr",
        193 => "fgetxattr",
        194 => "listxattr",
        195 => "llistxattr",
        196 => "flistxattr",
        197 => "removexattr",
        198 => "lremovexattr",
        199 => "fremovexattr",
        200 => "tkill",
        201 => "time",
        202 => "futex",
        203 => "sched_setaffinity",
        204 => "sched_getaffinity",
        206 => "io_setup",
        207 => "io_destroy",
        208 => "io_getevents",
        209 => "io_submit",
        210 => "io_cancel",
        212 => "lookup_dcookie",
        213 => "epoll_create",
        217 => "getdents64",
        218 => "set_tid_address",
        219 => "restart_syscall",
        220 => "semtimedop",
        221 => "fadvise64",
        222 => "timer_create",
        223 => "timer_settime",
        224 => "timer_gettime",
        225 => "timer_getoverrun",
        226 => "timer_delete",
        227 => "clock_settime",
        228 => "clock_gettime",
        229 => "clock_getres",
        230 => "clock_nanosleep",
        231 => "exit_group",
        232 => "epoll_wait",
        233 => "epoll_ctl",
        234 => "tgkill",
        235 => "utimes",
        237 => "mbind",
        238 => "set_mempolicy",
        239 => "get_mempolicy",
        240 => "mq_open",
        241 => "mq_unlink",
        242 => "mq_timedsend",
        243 => "mq_timedreceive",
        244 => "mq_notify",
        245 => "mq_getsetattr",
        246 => "kexec_load",
        247 => "waitid",
        248 => "add_key",
        249 => "request_key",
        250 => "keyctl",
        251 => "ioprio_set",
        252 => "ioprio_get",
        253 => "inotify_init",
        254 => "inotify_add_watch",
        255 => "inotify_rm_watch",
        256 => "migrate_pages",
        257 => "openat",
        258 => "mkdirat",
        259 => "mknodat",
        260 => "fchownat",
        261 => "futimesat",
        262 => "newfstatat",
        263 => "unlinkat",
        264 => "renameat",
        265 => "linkat",
        266 => "symlinkat",
        267 => "readlinkat",
        268 => "fchmodat",
        269 => "faccessat",
        270 => "pselect6",
        271 => "ppoll",
        272 => "unshare",
        273 => "set_robust_list",
        274 => "get_robust_list",
        275 => "splice",
        276 => "tee",
        277 => "sync_file_range",
        278 => "vmsplice",
        279 => "move_pages",
        280 => "utimensat",
        281 => "epoll_pwait",
        282 => "signalfd",
        283 => "timerfd_create",
        284 => "eventfd",
        285 => "fallocate",
        286 => "timerfd_settime",
        287 => "timerfd_gettime",
        288 => "accept4",
        289 => "signalfd4",
        290 => "eventfd2",
        291 => "epoll_create1",
        292 => "dup3",
        293 => "pipe2",
        294 => "inotify_init1",
        295 => "preadv",
        296 => "pwritev",
        297 => "rt_tgsigqueueinfo",
        298 => "perf_event_open",
        299 => "recvmmsg",
        300 => "fanotify_init",
        301 => "fanotify_mark",
        302 => "prlimit64",
        303 => "name_to_handle_at",
        304 => "open_by_handle_at",
        305 => "clock_adjtime",
        306 => "syncfs",
        307 => "sendmmsg",
        308 => "setns",
        309 => "getcpu",
        310 => "process_vm_readv",
        311 => "process_vm_writev",
        312 => "kcmp",
        313 => "finit_module",
        314 => "sched_setattr",
        315 => "sched_getattr",
        316 => "renameat2",
        317 => "seccomp",
        318 => "getrandom",
        319 => "memfd_create",
        320 => "kexec_file_load",
        321 => "bpf",
        322 => "execveat",
        323 => "userfaultfd",
        324 => "membarrier",
        325 => "mlock2",
        326 => "copy_file_range",
        327 => "preadv2",
        328 => "pwritev2",
        329 => "pkey_mprotect",
        330 => "pkey_alloc",
        331 => "pkey_free",
        332 => "statx",
        _ => return format!("syscall_{}", number),
    }
    .to_string()
}

/// ARM (32-bit) syscalls
fn arm_syscall_name(number: u32) -> String {
    match number {
        1 => "exit",
        2 => "fork",
        3 => "read",
        4 => "write",
        5 => "open",
        6 => "close",
        7 => "waitpid",
        9 => "link",
        10 => "unlink",
        11 => "execve",
        12 => "chdir",
        14 => "mknod",
        15 => "chmod",
        19 => "lseek",
        20 => "getpid",
        21 => "mount",
        23 => "setuid",
        24 => "getuid",
        26 => "ptrace",
        33 => "access",
        36 => "sync",
        37 => "kill",
        38 => "rename",
        39 => "mkdir",
        40 => "rmdir",
        41 => "dup",
        42 => "pipe",
        45 => "brk",
        54 => "ioctl",
        55 => "fcntl",
        60 => "umask",
        61 => "chroot",
        63 => "dup2",
        64 => "getppid",
        66 => "setsid",
        72 => "sigsuspend",
        78 => "gettimeofday",
        83 => "symlink",
        85 => "readlink",
        90 => "mmap",
        91 => "munmap",
        93 => "ftruncate",
        94 => "fchmod",
        95 => "fchown",
        102 => "socketcall",
        106 => "stat",
        107 => "lstat",
        108 => "fstat",
        114 => "wait4",
        116 => "sysinfo",
        120 => "clone",
        122 => "uname",
        125 => "mprotect",
        140 => "_llseek",
        141 => "getdents",
        142 => "_newselect",
        145 => "readv",
        146 => "writev",
        162 => "nanosleep",
        163 => "mremap",
        168 => "poll",
        174 => "rt_sigaction",
        175 => "rt_sigprocmask",
        183 => "getcwd",
        190 => "vfork",
        192 => "mmap2",
        195 => "stat64",
        196 => "lstat64",
        197 => "fstat64",
        217 => "pivot_root",
        219 => "madvise",
        220 => "getdents64",
        221 => "fcntl64",
        224 => "gettid",
        238 => "tkill",
        240 => "futex",
        241 => "sched_setaffinity",
        242 => "sched_getaffinity",
        248 => "exit_group",
        250 => "epoll_create",
        251 => "epoll_ctl",
        252 => "epoll_wait",
        263 => "clock_gettime",
        268 => "tgkill",
        280 => "socket",
        281 => "bind",
        282 => "connect",
        283 => "listen",
        284 => "accept",
        285 => "getsockname",
        286 => "getpeername",
        287 => "socketpair",
        288 => "send",
        289 => "sendto",
        290 => "recv",
        291 => "recvfrom",
        292 => "shutdown",
        293 => "setsockopt",
        294 => "getsockopt",
        295 => "sendmsg",
        296 => "recvmsg",
        322 => "openat",
        323 => "mkdirat",
        324 => "mknodat",
        325 => "fchownat",
        327 => "fstatat64",
        328 => "unlinkat",
        329 => "renameat",
        330 => "linkat",
        331 => "symlinkat",
        332 => "readlinkat",
        333 => "fchmodat",
        334 => "faccessat",
        _ => return format!("syscall_{}", number),
    }
    .to_string()
}

/// AArch64 syscalls
fn aarch64_syscall_name(number: u32) -> String {
    match number {
        0 => "io_setup",
        1 => "io_destroy",
        2 => "io_submit",
        3 => "io_cancel",
        4 => "io_getevents",
        5 => "setxattr",
        6 => "lsetxattr",
        7 => "fsetxattr",
        8 => "getxattr",
        9 => "lgetxattr",
        10 => "fgetxattr",
        11 => "listxattr",
        12 => "llistxattr",
        13 => "flistxattr",
        14 => "removexattr",
        15 => "lremovexattr",
        16 => "fremovexattr",
        17 => "getcwd",
        18 => "lookup_dcookie",
        19 => "eventfd2",
        20 => "epoll_create1",
        21 => "epoll_ctl",
        22 => "epoll_pwait",
        23 => "dup",
        24 => "dup3",
        25 => "fcntl",
        26 => "inotify_init1",
        27 => "inotify_add_watch",
        28 => "inotify_rm_watch",
        29 => "ioctl",
        30 => "ioprio_set",
        31 => "ioprio_get",
        32 => "flock",
        33 => "mknodat",
        34 => "mkdirat",
        35 => "unlinkat",
        36 => "symlinkat",
        37 => "linkat",
        38 => "renameat",
        39 => "umount2",
        40 => "mount",
        41 => "pivot_root",
        43 => "statfs",
        44 => "fstatfs",
        45 => "truncate",
        46 => "ftruncate",
        47 => "fallocate",
        48 => "faccessat",
        49 => "chdir",
        50 => "fchdir",
        51 => "chroot",
        52 => "fchmod",
        53 => "fchmodat",
        54 => "fchownat",
        55 => "fchown",
        56 => "openat",
        57 => "close",
        58 => "vhangup",
        59 => "pipe2",
        60 => "quotactl",
        61 => "getdents64",
        62 => "lseek",
        63 => "read",
        64 => "write",
        65 => "readv",
        66 => "writev",
        67 => "pread64",
        68 => "pwrite64",
        69 => "preadv",
        70 => "pwritev",
        71 => "sendfile",
        72 => "pselect6",
        73 => "ppoll",
        74 => "signalfd4",
        75 => "vmsplice",
        76 => "splice",
        77 => "tee",
        78 => "readlinkat",
        79 => "fstatat",
        80 => "fstat",
        81 => "sync",
        82 => "fsync",
        83 => "fdatasync",
        84 => "sync_file_range",
        85 => "timerfd_create",
        86 => "timerfd_settime",
        87 => "timerfd_gettime",
        88 => "utimensat",
        89 => "acct",
        90 => "capget",
        91 => "capset",
        92 => "personality",
        93 => "exit",
        94 => "exit_group",
        95 => "waitid",
        96 => "set_tid_address",
        97 => "unshare",
        98 => "futex",
        99 => "set_robust_list",
        100 => "get_robust_list",
        101 => "nanosleep",
        102 => "getitimer",
        103 => "setitimer",
        104 => "kexec_load",
        105 => "init_module",
        106 => "delete_module",
        107 => "timer_create",
        108 => "timer_gettime",
        109 => "timer_getoverrun",
        110 => "timer_settime",
        111 => "timer_delete",
        112 => "clock_settime",
        113 => "clock_gettime",
        114 => "clock_getres",
        115 => "clock_nanosleep",
        116 => "syslog",
        117 => "ptrace",
        118 => "sched_setparam",
        119 => "sched_setscheduler",
        120 => "sched_getscheduler",
        121 => "sched_getparam",
        122 => "sched_setaffinity",
        123 => "sched_getaffinity",
        124 => "sched_yield",
        125 => "sched_get_priority_max",
        126 => "sched_get_priority_min",
        127 => "sched_rr_get_interval",
        128 => "restart_syscall",
        129 => "kill",
        130 => "tkill",
        131 => "tgkill",
        132 => "sigaltstack",
        133 => "rt_sigsuspend",
        134 => "rt_sigaction",
        135 => "rt_sigprocmask",
        136 => "rt_sigpending",
        137 => "rt_sigtimedwait",
        138 => "rt_sigqueueinfo",
        139 => "rt_sigreturn",
        140 => "setpriority",
        141 => "getpriority",
        142 => "reboot",
        143 => "setregid",
        144 => "setgid",
        145 => "setreuid",
        146 => "setuid",
        147 => "setresuid",
        148 => "getresuid",
        149 => "setresgid",
        150 => "getresgid",
        151 => "setfsuid",
        152 => "setfsgid",
        153 => "times",
        154 => "setpgid",
        155 => "getpgid",
        156 => "getsid",
        157 => "setsid",
        158 => "getgroups",
        159 => "setgroups",
        160 => "uname",
        161 => "sethostname",
        162 => "setdomainname",
        163 => "getrlimit",
        164 => "setrlimit",
        165 => "getrusage",
        166 => "umask",
        167 => "prctl",
        168 => "getcpu",
        169 => "gettimeofday",
        170 => "settimeofday",
        171 => "adjtimex",
        172 => "getpid",
        173 => "getppid",
        174 => "getuid",
        175 => "geteuid",
        176 => "getgid",
        177 => "getegid",
        178 => "gettid",
        179 => "sysinfo",
        180 => "mq_open",
        181 => "mq_unlink",
        182 => "mq_timedsend",
        183 => "mq_timedreceive",
        184 => "mq_notify",
        185 => "mq_getsetattr",
        186 => "msgget",
        187 => "msgctl",
        188 => "msgrcv",
        189 => "msgsnd",
        190 => "semget",
        191 => "semctl",
        192 => "semtimedop",
        193 => "semop",
        194 => "shmget",
        195 => "shmctl",
        196 => "shmat",
        197 => "shmdt",
        198 => "socket",
        199 => "socketpair",
        200 => "bind",
        201 => "listen",
        202 => "accept",
        203 => "connect",
        204 => "getsockname",
        205 => "getpeername",
        206 => "sendto",
        207 => "recvfrom",
        208 => "setsockopt",
        209 => "getsockopt",
        210 => "shutdown",
        211 => "sendmsg",
        212 => "recvmsg",
        213 => "readahead",
        214 => "brk",
        215 => "munmap",
        216 => "mremap",
        217 => "add_key",
        218 => "request_key",
        219 => "keyctl",
        220 => "clone",
        221 => "execve",
        222 => "mmap",
        223 => "fadvise64",
        224 => "swapon",
        225 => "swapoff",
        226 => "mprotect",
        227 => "msync",
        228 => "mlock",
        229 => "munlock",
        230 => "mlockall",
        231 => "munlockall",
        232 => "mincore",
        233 => "madvise",
        234 => "remap_file_pages",
        235 => "mbind",
        236 => "get_mempolicy",
        237 => "set_mempolicy",
        238 => "migrate_pages",
        239 => "move_pages",
        240 => "rt_tgsigqueueinfo",
        241 => "perf_event_open",
        242 => "accept4",
        243 => "recvmmsg",
        260 => "wait4",
        261 => "prlimit64",
        262 => "fanotify_init",
        263 => "fanotify_mark",
        264 => "name_to_handle_at",
        265 => "open_by_handle_at",
        266 => "clock_adjtime",
        267 => "syncfs",
        268 => "setns",
        269 => "sendmmsg",
        270 => "process_vm_readv",
        271 => "process_vm_writev",
        272 => "kcmp",
        273 => "finit_module",
        274 => "sched_setattr",
        275 => "sched_getattr",
        276 => "renameat2",
        277 => "seccomp",
        278 => "getrandom",
        279 => "memfd_create",
        280 => "bpf",
        281 => "execveat",
        282 => "userfaultfd",
        283 => "membarrier",
        284 => "mlock2",
        285 => "copy_file_range",
        286 => "preadv2",
        287 => "pwritev2",
        288 => "pkey_mprotect",
        289 => "pkey_alloc",
        290 => "pkey_free",
        291 => "statx",
        _ => return format!("syscall_{}", number),
    }
    .to_string()
}

/// PowerPC syscalls
fn ppc_syscall_name(number: u32) -> String {
    match number {
        1 => "exit",
        2 => "fork",
        3 => "read",
        4 => "write",
        5 => "open",
        6 => "close",
        7 => "waitpid",
        9 => "link",
        10 => "unlink",
        11 => "execve",
        12 => "chdir",
        13 => "time",
        14 => "mknod",
        15 => "chmod",
        19 => "lseek",
        20 => "getpid",
        21 => "mount",
        23 => "setuid",
        24 => "getuid",
        26 => "ptrace",
        33 => "access",
        36 => "sync",
        37 => "kill",
        38 => "rename",
        39 => "mkdir",
        40 => "rmdir",
        41 => "dup",
        42 => "pipe",
        45 => "brk",
        54 => "ioctl",
        55 => "fcntl",
        60 => "umask",
        61 => "chroot",
        63 => "dup2",
        64 => "getppid",
        66 => "setsid",
        72 => "sigsuspend",
        78 => "gettimeofday",
        83 => "symlink",
        85 => "readlink",
        90 => "mmap",
        91 => "munmap",
        93 => "ftruncate",
        94 => "fchmod",
        95 => "fchown",
        102 => "socketcall",
        106 => "stat",
        107 => "lstat",
        108 => "fstat",
        114 => "wait4",
        116 => "sysinfo",
        120 => "clone",
        122 => "uname",
        125 => "mprotect",
        141 => "getdents",
        145 => "readv",
        146 => "writev",
        162 => "nanosleep",
        163 => "mremap",
        168 => "poll",
        174 => "rt_sigaction",
        175 => "rt_sigprocmask",
        183 => "getcwd",
        190 => "vfork",
        220 => "getdents64",
        224 => "gettid",
        234 => "exit_group",
        249 => "epoll_create",
        250 => "epoll_ctl",
        251 => "epoll_wait",
        259 => "tgkill",
        _ => return format!("syscall_{}", number),
    }
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_mips_syscalls() {
        assert_eq!(syscall_name("mips", 4001), "exit");
        assert_eq!(syscall_name("mips", 4002), "fork");
        assert_eq!(syscall_name("mips", 4003), "read");
        assert_eq!(syscall_name("mips", 4004), "write");
        assert_eq!(syscall_name("mips", 4005), "open");
        assert_eq!(syscall_name("mips", 4006), "close");
        assert_eq!(syscall_name("mips", 4011), "execve");
        assert_eq!(syscall_name("mips", 4037), "kill");
        assert_eq!(syscall_name("mips", 4066), "setsid");
        assert_eq!(syscall_name("mips", 4170), "connect");
        assert_eq!(syscall_name("mips", 4183), "socket");
        assert_eq!(syscall_name("mips", 4252), "exit_group");
    }

    #[test]
    fn test_x86_syscalls() {
        assert_eq!(syscall_name("x86", 1), "exit");
        assert_eq!(syscall_name("x86", 2), "fork");
        assert_eq!(syscall_name("x86", 3), "read");
        assert_eq!(syscall_name("x86", 4), "write");
        assert_eq!(syscall_name("x86", 11), "execve");
        assert_eq!(syscall_name("x86", 37), "kill");
        assert_eq!(syscall_name("x86", 66), "setsid");
        assert_eq!(syscall_name("x86", 102), "socketcall");
        assert_eq!(syscall_name("x86", 252), "exit_group");
    }

    #[test]
    fn test_x86_64_syscalls() {
        assert_eq!(syscall_name("x86_64", 0), "read");
        assert_eq!(syscall_name("x86_64", 1), "write");
        assert_eq!(syscall_name("x86_64", 41), "socket");
        assert_eq!(syscall_name("x86_64", 42), "connect");
        assert_eq!(syscall_name("x86_64", 57), "fork");
        assert_eq!(syscall_name("x86_64", 59), "execve");
        assert_eq!(syscall_name("x86_64", 60), "exit");
        assert_eq!(syscall_name("x86_64", 62), "kill");
        assert_eq!(syscall_name("x86_64", 112), "setsid");
        assert_eq!(syscall_name("x86_64", 231), "exit_group");
    }

    #[test]
    fn test_arm_syscalls() {
        assert_eq!(syscall_name("arm", 1), "exit");
        assert_eq!(syscall_name("arm", 3), "read");
        assert_eq!(syscall_name("arm", 4), "write");
        assert_eq!(syscall_name("arm", 11), "execve");
        assert_eq!(syscall_name("arm", 66), "setsid");
        assert_eq!(syscall_name("arm", 280), "socket");
        assert_eq!(syscall_name("arm", 282), "connect");
    }

    #[test]
    fn test_aarch64_syscalls() {
        assert_eq!(syscall_name("aarch64", 63), "read");
        assert_eq!(syscall_name("aarch64", 64), "write");
        assert_eq!(syscall_name("aarch64", 93), "exit");
        assert_eq!(syscall_name("aarch64", 129), "kill");
        assert_eq!(syscall_name("aarch64", 157), "setsid");
        assert_eq!(syscall_name("aarch64", 198), "socket");
        assert_eq!(syscall_name("aarch64", 203), "connect");
        assert_eq!(syscall_name("aarch64", 221), "execve");
    }

    #[test]
    fn test_unknown_syscall() {
        assert_eq!(syscall_name("mips", 9999), "syscall_9999");
        assert_eq!(syscall_name("x86_64", 9999), "syscall_9999");
        assert_eq!(syscall_name("unknown_arch", 1), "syscall_1");
    }
}
