traits:
  - id: bytecode-virus-project-name
    desc: "Cheshire Virus project name in settings.gradle"
    crit: suspicious
    conf: 1.0
    if:
      type: raw
      regex: "rootProject\\.name\\s*=\\s*['\"]BytecodeVirus['\"]"